Repository bratislava/bratislava.sk, pull requests merged in 2022-12, with the labels that each got.

#410 FORM-195: Refactor all category-color-100
  next/components/atoms/HeaderItem.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordion.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructureTopLevelAccordion.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/MinimumCalculator.tsx
  next/components/molecules/sections/rentpage/Accordion.tsx
  next/components/pages/blogPostPage.tsx
  next/components/pages/generalPage.tsx
  next/components/ui/AccordionItem/AccordionItem.tsx
  next/components/ui/AccordionItemSmall/AccordionItemSmall.tsx
  next/components/ui/AdvancedAccordionItem/AdvancedAccordionItem.tsx
  next/components/ui/AdvancedAccordionSubitem/AdvancedAccordionSubitem.tsx
  next/components/ui/Button/Button.tsx
  next/components/ui/Card/Card.tsx
  next/components/ui/Contact/Contact.tsx
  next/components/ui/DateSelect/DateSelect.tsx
  next/components/ui/DiagramCard/DiagramCard.tsx
  next/components/ui/FooterCard/FooterCard.tsx
  next/components/ui/HamburgerMenu/HamburgerMenu.tsx
  next/components/ui/HomepageMenu/HomepageMenu.tsx
  next/components/ui/ImageCard/ImageCard.tsx
  next/components/ui/NumericalListSection/NumericalListSection.tsx
  next/components/ui/PageCard/PageCard.tsx
  next/components/ui/PageHeader/PageHeader.tsx
  next/components/ui/Rent/Rent.tsx
  next/components/ui/SectionContainer/SectionContainer.tsx
  next/components/ui/Sections/RentAccordion/RentAccordion.tsx
  next/components/ui/StepperStep/StepperStep.tsx
  next/components/ui/SwitchToggle/SwitchToggle.tsx
  next/components/ui/TimeCardMobile/TimeCardMobile.tsx
  next/components/ui/Tooltip/Tooltip.tsx
  next/components/ui/WelcomeCard/WelcomeCard.tsx
  next/pages/bratislava.css
  next/pages/form/[eform].tsx
  next/pages/index.tsx
  next/pages/mesto-bratislava/transparentne-mesto/uradna-tabula.tsx
  next/pages/vyhladavanie.tsx
  next/utils/page.ts
Labels: fix & ship :ship:

#415 FORM-174: Fix date picker after review
  next/components/forms/DateTimePicker/Calendar/Calendar.tsx
  next/components/forms/DateTimePicker/Calendar/CalendarCell.tsx
  next/components/forms/DateTimePicker/Calendar/CalendarGrid.tsx
  next/components/forms/DateTimePicker/DateField.tsx
  next/components/forms/DateTimePicker/DatePicker.tsx
  next/components/forms/DateTimePicker/Popover.tsx
  next/components/styleguide/Stack.tsx
  next/components/styleguide/StyleGuideWrapper.tsx
Labels: fix & ship :ship:

#427 BA-736 add otherEmails attribute to show in organisational structure …
  next/backend/services/ms-graph.ts
  next/components/molecules/OrganizationalStructure/OrganizationalStructure.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordionCards.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructureTopLevelAccordion.tsx
  next/components/molecules/SearchPage/UsersResults.tsx
  next/components/ui/AccordionCard/AccordionCard.tsx
  next/components/ui/BANavBar/BANavBar.tsx
Labels: fix & ship :ship:

#412 FORM-201: RJSF - Fields - InputField
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/InputField.tsx
  next/components/forms/ThemedForm.tsx
  next/components/forms/widgets/InputFieldWidgetRJSF.tsx
  next/components/styleguide/showcases/InputFieldShowCase.tsx
Labels: fix & ship :ship:

#431 FORM-226/rjsf-changes
  next/backend/forms/test/schema.json
  next/components/forms/widgets/TextAreaFieldWidgetRJSF.tsx
Labels: fix & ship :ship:

#419 FORM-175: Fix Time Picker after review
  next/components/forms/DateTimePicker/TimeField.tsx
  next/components/forms/DateTimePicker/TimePicker.tsx
  next/components/forms/DateTimePicker/TimeSelector.tsx
  next/components/styleguide/showcases/TimePickerShowCase.tsx
Labels: fix & ship :ship:

#425 Form-202/RJSF-Checkboxes
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/CheckboxGroup.tsx
  next/components/forms/ThemedForm.tsx
  next/components/forms/widgets/CheckboxWidgetRJSF.tsx
  next/components/styleguide/showcases/CheckboxGroupedShowCase.tsx
Labels: fix & ship :ship:

#438 Meilisearch bugfix
  strapi/kubernetes/base/stateful-set-meilisearch.yml
Labels: infrastructure

#435 BA-725: add homepage search with suggestions
  next/assets/images/index.ts
  next/backend/meili/fetchers/homepageFetcher.ts
  next/backend/meili/types.ts
  next/components/atoms/AnimateHeight.tsx
  next/components/molecules/HomePageSearch.tsx
  next/components/molecules/HomePageSearchField.tsx
  next/components/molecules/HomePageSearchResults.tsx
  next/components/molecules/sections/documentList/DocumentList.tsx
  next/components/molecules/sections/documentList/DocumentListModalBody.tsx
  next/components/molecules/sections/documentList/DocumentListResults.tsx
  next/components/sections/WelcomeSection.tsx
  next/components/ui/Button/Button.tsx
  next/components/ui/DocumentListItem/DocumentListItem.tsx
  next/graphql/index.ts
  next/graphql/queries/Homepage.graphql
  next/package.json
  next/pages/index.tsx
  next/pages/vyhladavanie.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/yarn.lock
  strapi/src/components/blocks/homepage-header.json
Labels: needs review :pray:

#426 FORM-217: xml to json
  next/__tests__/forms/dopravneZnacenie.test.ts
  next/__tests__/forms/kontajneroveStojiska.test.ts
  next/__tests__/forms/zavazneStanoviskoKInvesticnejCinnosti.test.ts
  next/__tests__/utils/forms.test.ts
  next/backend/forms/00603481.dopravneZnacenie.sk/data.json
  next/backend/forms/index.ts
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/data.json
  next/backend/utils/forms.ts
  next/pages/api/eforms/[id]/transform/xmlToJson.ts
Labels: fix & ship :ship:

#439 Fix: Make cards on homepage clickable properly
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/BlogSearchCard/BlogSearchCard.tsx
  next/components/ui/DocumentCard/DocumentCard.tsx
  next/components/ui/DocumentListItem/DocumentListItem.tsx
  next/components/ui/HorizontalCard/HorizontalCard.tsx
  next/components/ui/InBaCard/InBaCard.tsx
  next/components/ui/NewsCard/NewsCard.tsx
  next/components/ui/PrimatorCard/PrimatorCard.tsx
  next/components/ui/Rent/Rent.tsx
  next/components/ui/Sections/BlogCards/BlogCards.tsx
  next/components/ui/Sections/Posts/Posts.tsx
  next/components/ui/TopNineItem/TopNineItem.tsx
  next/package.json
  next/pages/index.css
  next/tailwind.config.js
  next/yarn.lock
Labels: fix & ship :ship:

#434 FORM-201: Fix input field type and add zip type
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/InputField.tsx
  next/components/forms/widgets/InputFieldWidgetRJSF.tsx
  next/pages/bratislava.css
  next/pages/form/[eform].tsx
Labels: fix & ship :ship:

#443 BA-740: refactor icons in homepage menu
  next/components/atoms/button/MenuButton.tsx
  next/components/ui/HomepageMenu/HomePageCategoryButton.tsx
  next/components/ui/HomepageMenu/HomepageMenu.tsx
  next/components/ui/HomepageMenu/HomepageMenuIcon.tsx
  next/components/ui/HomepageMenu/IconComponents/IconCulture.tsx
  next/components/ui/HomepageMenu/IconComponents/IconEducation.tsx
  next/components/ui/HomepageMenu/IconComponents/IconEnvironment.tsx
  next/components/ui/HomepageMenu/IconComponents/IconMain.tsx
  next/components/ui/HomepageMenu/IconComponents/IconSocial.tsx
  next/components/ui/HomepageMenu/IconComponents/IconTransport.tsx
  next/components/ui/HomepageMenu/MenuDesktopLayout.tsx
Labels: needs review :pray:

#447 BA-740 remove unused field iconHover from strapi
  next/components/ui/HomepageMenu/HomePageCategoryButton.tsx
  next/components/ui/HomepageMenu/HomepageMenu.tsx
  next/components/ui/HomepageMenu/HomepageMenuIcon.tsx
  next/graphql/index.ts
  next/graphql/queries/Pages.graphql
  next/utils/page.ts
  strapi/src/api/page-category/content-types/page-category/schema.json
Labels: needs review :pray:

#400 BA-572: Fix overlapping subpage headlines
  next/.eslintrc.js
  next/components/ui/SubpageList/SubpageList.tsx
Labels: needs review :pray:

#444 Reverted meilisearch settings
  strapi/kubernetes/base/stateful-set-meilisearch.yml
Labels: infrastructure

#450 Form-186/Fix accordion component
  next/components/forms/simple-components/Accordion.tsx
  next/components/styleguide/showcases/AccordionShowCase.tsx
Labels: fix & ship :ship:

#449 Form-184/Fix progress bar responsive view
  next/components/styleguide/showcases/ProgressBarShowCase.tsx
Labels: fix & ship :ship:

#452 Upgrade strapi to v4.4
  strapi/package.json
  strapi/yarn.lock
Labels: needs review :pray:

#454 Form 186/fix accordion styles
  next/components/forms/simple-components/Accordion.tsx
Labels: fix & ship :ship:

#457 Form-173/Fix fontsize
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
Labels: fix & ship :ship:

#460 Ba 743
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordionCards.tsx
  next/components/ui/AccordionCard/AccordionCard.tsx
  next/components/ui/Sections/RentBenefits/RentBenefits.tsx
Labels: needs review :pray:

#285 BA-161 - Introduced gallery component
  docs/mapping.md
  next/assets/images/icon-eye-white.svg
  next/components/molecules/PageBreadcrumbs.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/Gallery.tsx
  next/components/pages/generalPage.tsx
  next/components/ui/FileList/FileList.tsx
  next/components/ui/Modal/Modal.tsx
  next/graphql/index.ts
  next/graphql/queries/Pages.graphql
  next/next.config.js
  next/pages/typography.css
  next/public/locales/sk/common.json
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/blocks/gallery-item.json
  strapi/src/components/sections/gallery.json
Labels: fix & ship :ship:

#461 BA-721,BA-699,BA-744: change goout event to show only BA and BKIS events, sordted by criterias
  next/components/atoms/CardGradient.tsx
  next/components/molecules/HomePageSearchField.tsx
  next/components/molecules/sections/homepage/GooutEvents.tsx
  next/components/ui/Carousel/Carousel.tsx
  next/components/ui/HamburgerSubMenu/HamburgerSubMenu.tsx
  next/components/ui/HomepageMenu/MenuMobileLayout.tsx
  next/components/ui/InBaCard/InBaCard.tsx
  next/components/ui/Link/Link.tsx
  next/components/ui/Sections/BlogCards/BlogCards.tsx
  next/pages/index.tsx
  next/utils/goout.ts
  next/utils/parseGooutScheduleResponse.ts
Labels: fix & ship :ship:

#456 Form-168/Fix radio-button
  next/components/forms/widget-components/RadioButton/Radio.tsx
  next/components/styleguide/showcases/RadioButtonShowCase.tsx
Labels: fix & ship :ship:

#448 Fix react-aria warnings
  next/components/forms/simple-components/ProgressBar.tsx
  next/components/forms/widget-components/Checkbox/Checkbox.tsx
  next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
  next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
  next/components/styleguide/showcases/CheckboxGroupedShowCase.tsx
  next/components/styleguide/showcases/ProgressBarShowCase.tsx
  next/components/styleguide/showcases/RadioButtonShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#458 FORM-201: Fix reset icon color
  next/assets/images/forms/circle-filled-reset.svg
  next/components/forms/widget-components/InputField/InputField.tsx
Labels: fix & ship :ship:

#453 Form-177/upload-fix
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/info-components/UploadBrokenMessages.tsx
  next/components/forms/info-components/UploadFieldHeader.tsx
  next/components/forms/widget-components/Upload/Upload.tsx
  next/components/forms/widget-components/Upload/UploadDropArea.tsx
  next/components/forms/widget-components/Upload/UploadedFile.tsx
  next/components/forms/widget-components/Upload/UploadedFilesList.tsx
  next/components/forms/widget-wrappers/UploadWidgetRJSF.tsx
  next/components/styleguide/showcases/UploadShowCase.tsx
  next/pages/bratislava.css
Labels: fix & ship :ship:

#464 Form-206/rjsf-select-fix
  next/backend/forms/test/schema.json
  next/components/forms/widget-components/SelectField/Dropdown.tsx
  next/components/forms/widget-components/SelectField/DropdownRow.tsx
  next/components/forms/widget-components/SelectField/SelectAllDropdownRow.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
Labels: fix & ship :ship:

#413 Form-187/Modals
  next/assets/images/forms/arrow-left.svg
  next/components/forms/widget-components/Modals/MessageModal.tsx
  next/components/forms/widget-components/Modals/Modal.tsx
  next/components/styleguide/showcases/ModalShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#442 FORM-212: Form spacing
  next/backend/forms/test/uiSchema.json
  next/components/forms/types/WidgetOptions.ts
  next/components/forms/widget-components/Upload/UploadRJSFOptions.ts
  next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
  next/components/forms/widget-wrappers/InputFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
  next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TextAreaFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/UploadWidgetRJSF.tsx
  next/components/forms/widget-wrappers/WidgetWrapper.tsx
Labels: fix & ship :ship:

#451 FORM-221: test workflow
  .github/workflows/pull.yml
Labels: fix & ship :ship:

#468 FORM-222 docs
  next/__tests__/forms.test.ts
  next/__tests__/forms/dopravneZnacenie.test.ts
  next/__tests__/forms/kontajneroveStojiska.test.ts
  next/__tests__/forms/zavazneStanoviskoKInvesticnejCinnosti.test.ts
  next/backend/forms/dopravneZnacenie.ts
  next/backend/forms/index.ts
  next/backend/forms/kontajneroveStojiska.ts
  next/backend/forms/testForm.ts
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti.ts
  next/package.json
  next/yarn.lock
Labels: fix & ship :ship:

#422 BA-733: Refactor menu navigation
  next/components/atoms/icon/Icon.tsx
  next/components/layouts/BasePageLayout.tsx
  next/components/layouts/HomepagePageLayout.tsx
  next/components/sections/WelcomeSection.tsx
  next/components/sections/useWelcomeSection.ts
  next/components/ui/BAStickyMenu/BAStickyMenu.tsx
  next/components/ui/BAStickyMenu/MenuCell.tsx
  next/components/ui/BAStickyMenu/MenuPanel.tsx
  next/components/ui/BAStickyMenu/useStickyMenu.ts
  next/components/ui/HomepageMenu/HomePageCategoryButton.tsx
  next/components/ui/HomepageMenu/HomepageMenu.tsx
  next/components/ui/HomepageMenu/HomepageMenuPanel.tsx
  next/components/ui/HomepageMenu/useHomepageMenu.ts
  next/components/ui/Panel/Panel.tsx
  next/components/ui/VisibilityIntersection/useIntersectionObserver.ts
  next/components/utils/ClickOutsideHandler/useClickOutsideHandler.ts
  next/pages/index.tsx
Labels: needs work :hammer_and_wrench:

#470 FORM-201: Fix padding with reset icon and spacing handling
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
Labels: fix & ship :ship:

#463 Form-203/Radio-button RJSF fix
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
Labels: fix & ship :ship:

#469 Form-184/Fix: Label warning
  next/components/forms/simple-components/ProgressBar.tsx
  next/components/styleguide/showcases/ProgressBarShowCase.tsx
Labels: fix & ship :ship:

#473 Form-202/Fix Checkbox-RJSF logic
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
Labels: fix & ship :ship:

#466 FORM-208/rjsf-textarea-fix
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
Labels: fix & ship :ship:

#467 FROM-XXX: Fix translations on form pages
  next/components/forms/steps/FinalStep.tsx
  next/pages/form/[eform].tsx
Labels: needs review :pray:

#437 FORM-207: RJSF Date and Time Picker
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/ThemedForm.tsx
  next/components/forms/widget-components/DateTimePicker/Calendar/Calendar.tsx
  next/components/forms/widget-components/DateTimePicker/DatePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeSelector.tsx
  next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
  next/pages/form/[eform].tsx
Labels: fix & ship :ship:

#455 FORM-233: Error handling RJSF
  next/backend/forms/test/uiSchema.json
  next/components/forms/info-components/FieldErrorMessage.tsx
  next/components/forms/widget-components/DateTimePicker/DateField.tsx
  next/components/forms/widget-components/DateTimePicker/DatePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
  next/components/forms/widget-components/Upload/Upload.tsx
  next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/InputFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
  next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TextAreaFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/UploadWidgetRJSF.tsx
  next/components/styleguide/showcases/DatePickerShowCase.tsx
  next/components/styleguide/showcases/FieldHeaderShowCase.tsx
  next/components/styleguide/showcases/InputFieldShowCase.tsx
  next/components/styleguide/showcases/SearchFieldShowCase.tsx
  next/components/styleguide/showcases/SelectFieldShowCase.tsx
  next/components/styleguide/showcases/TextAreaFieldShowCase.tsx
  next/components/styleguide/showcases/TimePickerShowCase.tsx
  next/pages/form/[eform].tsx
Labels: fix & ship :ship:
