Repository bratislava/bratislava.sk, pull requests merged in 2022-11, with the labels that each got.

#350 Form-177/upload
  next/assets/images/forms/ball_delimiter_icon.svg
  next/assets/images/forms/pin_file_error_icon.svg
  next/assets/images/forms/pin_file_hover_icon.svg
  next/assets/images/forms/pin_file_icon.svg
  next/assets/images/forms/trash_bin_error_icon.svg
  next/assets/images/forms/trash_bin_icon.svg
  next/assets/images/forms/upload-icon.svg
  next/backend/dtos/minio/upload-minio-file.dto.ts
  next/backend/services/minio.ts
  next/backend/utils/minio-client.ts
  next/components/forms/Upload/Upload.tsx
  next/components/forms/Upload/UploadButton.tsx
  next/components/forms/Upload/UploadDropArea.tsx
  next/components/forms/Upload/UploadedFile.tsx
  next/components/styleguide/showcases/UploadShowCase.tsx
  next/package.json
  next/pages/api/eforms/delete-file.ts
  next/pages/api/eforms/upload-file.ts
  next/pages/styleguide.tsx
  next/tailwind.config.js
  next/tsconfig.json
  next/yarn.lock
Labels: fix & ship :ship:

#373 BA-722, BA-726: update header, quick fixes
  next/assets/images/phone-nav.svg
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/Brand/Brand.tsx
  next/components/ui/HamburgerMenu/HamburgerMenu.tsx
  next/components/ui/InBaCard/InBaCard.tsx
  next/pages/index.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/utils/constants.tsx
  next/utils/homepage-mockdata.ts
Labels: needs review :pray:

#371 Search - one index
  docker-compose.yml
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/.eslintrc.js
  next/backend/meili/fetchers/blogPostsFetcher.ts
  next/backend/meili/fetchers/pagesFetcher.ts
  next/backend/meili/fetchers/vznFetcher.ts
  next/backend/meili/meiliClient.ts
  next/backend/meili/types.ts
  next/backend/meili/utils.ts
  next/backend/utils/meili.ts
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordionCards.tsx
  next/components/molecules/SearchPage/BlogPostsResults.tsx
  next/components/molecules/SearchPage/LoadingOverlay.tsx
  next/components/molecules/SearchPage/PagesResults.tsx
  next/components/molecules/SearchPage/UsersResults.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/documentList/DocumentList.tsx
  next/components/molecules/sections/documentList/DocumentListModalBody.tsx
  next/components/molecules/sections/documentList/DocumentListResults.tsx
  next/components/molecules/sections/documentList/index.tsx
  next/components/ui/AccordionCard/AccordionCard.tsx
  next/components/ui/AdvancedAccordion/AdvancedAccordion.tsx
  next/components/ui/AdvancedSearch/AdvancedSearch.tsx
  next/components/ui/BasicSearch/BasicSearch.tsx
  next/components/ui/BasicSearchOld/BasicSearchOld.stories.mdx
  next/components/ui/BasicSearchOld/BasicSearchOld.tsx
  next/components/ui/BlogSearchCard/BlogSearchCard.tsx
  next/components/ui/BlogSearchCards/BlogSearchCards.tsx
  next/components/ui/FeaturedBlogs/FeaturedBlogs.tsx
  next/components/ui/LoadingSpinner/LoadingSpinner.tsx
  next/components/ui/Modal/Modal.tsx
  next/components/ui/PageCards/PageCards.tsx
  next/components/ui/SearchResults/SearchResults.tsx
  next/components/ui/SectionContainer/SectionContainer.tsx
  next/components/ui/index.ts
  next/package.json
  next/pages/_app.tsx
  next/pages/mesto-bratislava/transparentne-mesto/uradna-tabula.tsx
  next/pages/vyhladavanie.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/tsconfig.json
  next/utils/useGetSwrExtras.ts
  next/utils/usePrevious.ts
  next/utils/useScrollToViewIfDataChange.ts
  next/yarn.lock
  strapi/config/database.js
  strapi/config/plugins.js
  strapi/kubernetes/base/stateful-set-meilisearch.yml
  strapi/package.json
  strapi/src/admin/app.js
Labels: fix & ship :ship:

#372 BA-724: Show button content based on video length
  next/components/ui/Videos/Videos.tsx
  next/components/ui/Videos/VideosService.ts
Labels: fix & ship :ship:

#383 Fixes after search refactor
  .prettierrc
  next/.prettierrc
  next/backend/meili/meiliClient.ts
  next/backend/utils/organisationalStructure.ts
  next/components/molecules/SearchPage/BlogPostsResults.tsx
  next/components/molecules/SearchPage/LoadingOverlay.tsx
  next/components/molecules/sections/documentList/DocumentListModalBody.tsx
  next/components/molecules/sections/documentList/DocumentListResults.tsx
  next/components/ui/AdvancedAccordion/AdvancedAccordion.tsx
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/FileCard/FileCard.tsx
Labels: needs review :pray:

#368 Form 197/design system shadows
  next/tailwind.config.js
Labels: fix & ship :ship:

#384 FORM-172/Fix SearchField after review
  next/components/forms/SearchField.tsx
Labels: fix & ship :ship:

#386 Form-176/Fix Alert text aligning and screen responsivity
  next/components/forms/Alert.tsx
  next/components/styleguide/showcases/AlertShowCase.tsx
Labels: fix & ship :ship:

#396 BA-488: Create unused logic for intersection check
  next/components/ui/VisibilityIntersection/VisibilityIntersectionWrapper.tsx
  next/components/ui/VisibilityIntersection/useIntersectionObserver.ts
Labels: fix & ship :ship:

#395 FORM-177/upload-fix
  next/components/forms/Upload/UploadDropArea.tsx
Labels: fix & ship :ship:

#394 FORM-185/tooltip-fix
  next/components/forms/Tooltip.tsx
Labels: fix & ship :ship:

#392 BA-716: Revert grid class change
  next/components/atoms/ArticlesFilter.tsx
  next/components/molecules/sections/homepage/ArticlesList.tsx
  next/components/ui/NewsCard/NewsCard.tsx
Labels: fix & ship :ship:

#399 BA-731: Encapsulate header components
  next/components/sections/WelcomeSection.tsx
  next/components/ui/Bookmark/Bookmark.tsx
  next/components/ui/Sections/Posts/Posts.tsx
  next/pages/index.tsx
Labels: fix & ship :ship:

#407 Fixed Search Field component
  next/components/forms/SearchField.tsx
  next/components/styleguide/showcases/SearchFieldShowCase.tsx
Labels: fix & ship :ship:

#408 Form-176/Fixed Alert component
  next/components/forms/Alert.tsx
Labels: fix & ship :ship:

#385 Form-173/Fix TextAreaField after review
  next/components/forms/TextAreaField.tsx
  next/components/styleguide/showcases/TextAreaFieldShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#382 FORM-170/Fix InputField after review
  next/assets/images/forms/call.svg
  next/assets/images/forms/lock.svg
  next/assets/images/forms/mail.svg
  next/assets/images/forms/person.svg
  next/components/forms/FieldHeader.tsx
  next/components/forms/InputField.tsx
  next/components/styleguide/showcases/InputFieldShowCase.tsx
Labels: question :question:, fix & ship :ship:

#387 Form-168/Radio button
  next/components/forms/RadioButton/Radio.tsx
  next/components/forms/RadioButton/RadioGroup.tsx
  next/components/styleguide/showcases/RadioButtonShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#388 Form-169/Checkbox button
  next/components/forms/Checkbox.tsx
  next/components/forms/CheckboxGroup.tsx
  next/components/forms/SingleCheckbox.tsx
  next/components/styleguide/showcases/CheckboxGroupedShowCase.tsx
  next/components/styleguide/showcases/SingleCheckboxShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#416 FORM-218/fieldheader-fix
  next/components/forms/DateTimePicker/DateField.tsx
  next/components/forms/DateTimePicker/DatePicker.tsx
  next/components/forms/DateTimePicker/TimeField.tsx
  next/components/forms/DateTimePicker/TimePicker.tsx
  next/components/forms/FieldHeader.tsx
  next/components/forms/InputField.tsx
  next/components/forms/SearchField.tsx
  next/components/forms/SelectField/DropdownRow.tsx
  next/components/forms/SelectField/SelectField.tsx
  next/components/forms/SelectField/SelectFieldBox.tsx
  next/components/forms/TextAreaField.tsx
  next/components/forms/icon-components/RadioButtonIcon.tsx
  next/components/forms/widgets/SelectFieldWidgetRJSF.tsx
  next/components/styleguide/showcases/FieldHeaderShowCase.tsx
Labels: fix & ship :ship:

#414 Form-185/tooltip fix
  next/components/forms/Tooltip.tsx
Labels: fix & ship :ship:

#405 Form-208/rjsf-textarea
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/TextAreaField.tsx
  next/components/forms/ThemedForm.tsx
  next/components/forms/widgets/TextAreaFieldWidgetRJSF.tsx
Labels: fix & ship :ship:

#404 Fixed progress bar component via new tailwind config
  next/components/forms/ProgressBar.tsx
  next/components/styleguide/showcases/ProgressBarShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#406 Fixed Accordion component via new tailwind config
  next/components/forms/Accordion.tsx
  next/components/forms/icon-components/ExpandMoreIcon.tsx
  next/components/forms/icon-components/PersonIcon.tsx
  next/components/styleguide/showcases/AccordionShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#402 Form-204/rjsf upload
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/SelectField/DropdownRow.tsx
  next/components/forms/ThemedForm.tsx
  next/components/forms/Upload/Upload.tsx
  next/components/forms/Upload/UploadButton.tsx
  next/components/forms/Upload/UploadDropArea.tsx
  next/components/forms/Upload/UploadRJSFOptions.ts
  next/components/forms/Upload/UploadedFile.tsx
  next/components/forms/widgets/UploadWidgetRJSF.tsx
Labels: fix & ship :ship:

#423 Form-173/TextArea Fix responsive view for mobile screens
  next/components/forms/TextAreaField.tsx
  next/components/styleguide/showcases/TextAreaFieldShowCase.tsx
Labels: fix & ship :ship:

#424 Form-185/tooltip fix
  next/components/forms/Tooltip.tsx
Labels: fix & ship :ship:

#411 FORM-216 json to xml
  next/Dockerfile
  next/__tests__/forms/dopravneZnacenie.test.ts
  next/__tests__/forms/kontajneroveStojiska.test.ts
  next/__tests__/utils/forms.test.ts
  next/__tests__/utils/xslt.test.ts
  next/backend/forms/00603481.dopravneZnacenie.sk/data.json
  next/backend/forms/00603481.dopravneZnacenie.sk/data.xml.ts
  next/backend/forms/00603481.dopravneZnacenie.sk/form.fo.xslt
  next/backend/forms/00603481.dopravneZnacenie.sk/form.html.xslt
  next/backend/forms/00603481.dopravneZnacenie.sk/form.sb.xslt
  next/backend/forms/00603481.dopravneZnacenie.sk/schema.json
  next/backend/forms/00603481.dopravneZnacenie.sk/schema.xsd.ts
  next/backend/forms/00603481.dopravneZnacenie.sk/xmlTemplate.ts
  next/backend/forms/index.ts
  next/backend/forms/kontajneroveStojiska/data.json
  next/backend/forms/kontajneroveStojiska/data.xml.ts
  next/backend/forms/kontajneroveStojiska/form.fo.xslt
  next/backend/forms/kontajneroveStojiska/form.html.sef.json
  next/backend/forms/kontajneroveStojiska/form.html.xslt
  next/backend/forms/kontajneroveStojiska/form.sb.sef.json
  next/backend/forms/kontajneroveStojiska/form.sb.xslt
  next/backend/forms/kontajneroveStojiska/schema.json
  next/backend/forms/kontajneroveStojiska/schema.xsd.ts
  next/backend/forms/kontajneroveStojiska/uiSchema.json
  next/backend/forms/kontajneroveStojiska/xmlTemplate.ts
  next/backend/forms/test/data.json
  next/backend/forms/test/data.xml.ts
  next/backend/forms/test/form.fo.xslt
  next/backend/forms/test/form.html.sef.json
  next/backend/forms/test/form.html.xslt
  next/backend/forms/test/form.sb.sef.json
  next/backend/forms/test/form.sb.xslt
  next/backend/forms/test/schema.json
  next/backend/forms/test/schema.xsd.ts
  next/backend/forms/test/xmlTemplate.ts
  next/backend/utils/forms.ts
  next/backend/utils/strings.ts
  next/backend/utils/xslt.ts
  next/components/forms/widgets/SelectFieldWidgetRJSF.tsx
  next/jest.config.js
  next/jest.setup.js
  next/package.json
  next/pages/api/eforms/[id]/submit.ts
  next/pages/api/eforms/[id]/transform/html.ts
  next/pages/api/eforms/[id]/transform/text.ts
  next/pages/api/eforms/[id]/transform/xml.ts
  next/pages/form/[eform].tsx
  next/yarn.lock
Labels: fix & ship :ship:

#420 Form-203/RJSF Radio button
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/RadioButton/RadioGroup.tsx
  next/components/forms/ThemedForm.tsx
  next/components/forms/widgets/RadioButtonWidgetRJSF.tsx
  next/components/styleguide/showcases/RadioButtonShowCase.tsx
Labels: fix & ship :ship:
