Repository bratislava/bratislava.sk, pull requests merged in 2022-10, with the labels that each got.

#324 FORM-190: Create a styleguide page, add button component
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#323 FORM-166: add search-icon.svg to /assets/images/forms
  next/assets/images/forms/arrow-right.svg
  next/assets/images/forms/search-icon.svg
  next/components/forms/Button.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#330 Change .env.development STRAPI_URL, docs update
  README.md
  next/.env.development
  next/README.md
  strapi/README.md
Labels: documentation :writing_hand:, needs review :pray:

#329 Feat/field header
  next/assets/images/forms/icon-help.svg
  next/components/forms/FieldErrorMessage.tsx
  next/components/forms/FieldHeader.tsx
  next/pages/styleguide.tsx
Labels: needs work :hammer_and_wrench:

#336 Form 179/tag
  next/components/forms/Tag.tsx
  next/components/styleguide/showcases/TagShowCase.tsx
  next/pages/bratislava.css
  next/pages/styleguide.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#338 BA-694 erase hiding scrollbar on webkit devices
  next/pages/index.css
Labels: fix & ship :ship:

#341 Fixed button component sizes
  next/components/forms/Button.tsx
Labels: fix & ship :ship:

#339 FORM-174: Add DatePicker component, add to styleguide page examples
  next/assets/images/forms/calendar-icon.svg
  next/assets/images/forms/chevron-left.svg
  next/assets/images/forms/chevron-right.svg
  next/components/forms/DatePicker/Calendar/Calendar.tsx
  next/components/forms/DatePicker/Calendar/CalendarCell.tsx
  next/components/forms/DatePicker/Calendar/CalendarGrid.tsx
  next/components/forms/DatePicker/DateField.tsx
  next/components/forms/DatePicker/DatePicker.tsx
  next/components/forms/DatePicker/Popover.tsx
  next/components/styleguide/showcases/DatePickerShowCase.tsx
  next/next.config.js
  next/package.json
  next/pages/_app.tsx
  next/pages/styleguide.tsx
  next/tailwind.config.js
  next/yarn.lock
Labels: fix & ship :ship:

#340 Fix fonts on styleguide and 404 page
  next/components/styleguide/StyleGuideWrapper.tsx
  next/pages/404.tsx
Labels: needs review :pray:

#322 FORM-170: Create InputField.tsx, add icons
  next/assets/images/forms/circle-filled-reset.svg
  next/assets/images/forms/person.svg
  next/components/forms/InputField.tsx
  next/components/styleguide/showcases/InputFieldShowCase.tsx
  next/pages/styleguide.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#305 BA-685: Split backend code to own folder
  next/backend/dtos/ginis/api-data.dto.tsx
  next/backend/services/ginis.ts
  next/backend/services/ms-graph.ts
  next/backend/utils/cookies.ts
  next/backend/utils/ginis-service.ts
  next/backend/utils/meili.ts
  next/backend/utils/opendata.ts
  next/backend/utils/organisationalStructure.ts
  next/components/atoms/OrgStructurePersonCard.tsx
  next/components/layouts/PageWrapper.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructure.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordion.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordionCards.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructureTopLevelAccordion.tsx
  next/components/molecules/PageBreadcrumbs.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/charts/CyclingTotalChart.tsx
  next/components/molecules/sections/documentList/index.tsx
  next/components/molecules/sections/homepage/FacebookPosts.tsx
  next/components/molecules/sections/homepage/GooutEvents.tsx
  next/components/organisms/CookieConsent.tsx
  next/components/pages/blogPostPage.tsx
  next/components/pages/generalPage.tsx
  next/components/ui/AdvancedAccordionDepartment/AdvancedAccordionDepartment.tsx
  next/components/ui/AdvancedAccordionItem/AdvancedAccordionItem.tsx
  next/components/ui/AdvancedAccordionSubSubitem/AdvancedAccordionSubSubitem.tsx
  next/components/ui/AdvancedAccordionSubitem/AdvancedAccordionSubitem.tsx
  next/components/ui/DocumentCard/DocumentCard.tsx
  next/components/ui/DocumentCards/DocumentCards.tsx
  next/components/ui/SearchResults/SearchResults.tsx
  next/components/ui/Sections/Posts/Posts.tsx
  next/pages/[...slug].tsx
  next/pages/api/cycling.ts
  next/pages/api/facebook-posts.ts
  next/pages/api/ginis/document-detail/[id].ts
  next/pages/api/ginis/document-load-file/[id].ts
  next/pages/api/ginis/documents-list.ts
  next/pages/api/ginis/newest.ts
  next/pages/api/goout-events.ts
  next/pages/api/latest-blogposts.tsx
  next/pages/api/ms-graph/structure.ts
  next/pages/api/ms-graph/users/[email].ts
  next/pages/api/ms-graph/users/department/[department].ts
  next/pages/api/ms-graph/users/search/[query].tsx
  next/pages/blog/[slug].tsx
  next/pages/index.tsx
  next/pages/mesto-bratislava/transparentne-mesto/uradna-tabula.tsx
  next/pages/vyhladavanie.tsx
  next/utils/facebook.ts
  next/utils/page.ts
  next/utils/regex.ts
  next/utils/types.ts
  next/utils/utils.ts
Labels: fix & ship :ship:

#314 BA-555 Correct design issues in accordion item
  next/components/atoms/HomepageMarkdown.tsx
  next/components/molecules/Sections.tsx
  next/components/ui/AccordionItem/AccordionItem.tsx
  next/components/ui/NarrowText/NarrowText.tsx
  next/components/ui/NumericalListItem/NumericalListItem.tsx
  next/pages/index.css
Labels: fix & ship :ship:

#331 Form 171/fields select
  next/components/forms/FieldErrorMessage.tsx
  next/components/forms/SelectField.tsx
  next/components/forms/Tag.tsx
  next/components/styleguide/showcases/SelectFieldShowCase.tsx
  next/package.json
  next/pages/styleguide.tsx
  next/yarn.lock
Labels: fix & ship :ship:

#343 Geolocation for iframe
  next/components/ui/Iframe/Iframe.tsx
  next/graphql/index.ts
  next/graphql/queries/Pages.graphql
  strapi/src/components/sections/iframe.json
Labels: fix & ship :ship:

#345 basic style for toggle component
  next/components/forms/Toggle.tsx
  next/components/forms/icon-components/CheckedIcon.tsx
  next/components/forms/icon-components/UnCheckedIcon.tsx
  next/components/styleguide/showcases/ToggleShowCase.tsx
  next/pages/bratislava.css
  next/pages/styleguide.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#346 basic style for textarea component
  next/components/forms/TextAreaField.tsx
  next/components/styleguide/showcases/TextAreaFieldShowCase.tsx
  next/pages/styleguide.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#348 FORM-174: Add colors to tailwind.config, change color of input for disabled, focus today's day DON'T WORK
  next/components/forms/DatePicker/Calendar/CalendarGrid.tsx
  next/components/forms/DatePicker/DateField.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#344 basic style for spinner component
  next/components/forms/Spinner.tsx
  next/components/styleguide/showcases/SpinnerShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#351 feat: add forwardRef to SelectField
  next/components/forms/SelectField.tsx
  next/components/styleguide/showcases/SelectFieldShowCase.tsx
Labels: fix & ship :ship:

#347 basic style for search field component
  next/assets/images/forms/dark-search-icon.svg
  next/components/forms/SearchField.tsx
  next/components/styleguide/showcases/SearchFieldShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#354 Form 185/tooltip
  next/assets/images/forms/tooltip_left_arrow_icon.svg
  next/assets/images/forms/tooltip_top_arrow_icon.svg
  next/components/forms/FieldHeader.tsx
  next/components/forms/Tooltip.tsx
  next/components/styleguide/Wrapper.tsx
  next/components/styleguide/showcases/TooltipShowCase.tsx
  next/pages/bratislava.css
  next/pages/styleguide.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#352 FORM-175: Add component TimePicker
  next/assets/images/forms/access-time-icon.svg
  next/components/forms/DateTimePicker/Calendar/Calendar.tsx
  next/components/forms/DateTimePicker/Calendar/CalendarCell.tsx
  next/components/forms/DateTimePicker/Calendar/CalendarGrid.tsx
  next/components/forms/DateTimePicker/DateField.tsx
  next/components/forms/DateTimePicker/DatePicker.tsx
  next/components/forms/DateTimePicker/Popover.tsx
  next/components/forms/DateTimePicker/TimeField.tsx
  next/components/forms/DateTimePicker/TimePicker.tsx
  next/components/forms/DateTimePicker/TimeSelector.tsx
  next/components/styleguide/showcases/DatePickerShowCase.tsx
  next/components/styleguide/showcases/TimePickerShowCase.tsx
  next/package.json
  next/pages/styleguide.tsx
  next/tailwind.config.js
  next/utils/utils.ts
  next/yarn.lock
Labels: needs review :pray:

#349 basic style for alert component
  next/components/forms/Alert.tsx
  next/components/forms/icon-components/CloseIcon.tsx
  next/components/forms/icon-components/ErrorIcon.tsx
  next/components/forms/icon-components/InfoIcon.tsx
  next/components/forms/icon-components/SuccessIcon.tsx
  next/components/forms/icon-components/WarningIcon.tsx
  next/components/styleguide/showcases/AlertShowCase.tsx
  next/pages/styleguide.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:

#356 FORM-192 text and html transform
  next/__tests__/utils/xslt.test.ts
  next/backend/forms/00603481.dopravneZnacenie.sk/data.xml
  next/backend/forms/00603481.dopravneZnacenie.sk/form.html.sef.json
  next/backend/forms/00603481.dopravneZnacenie.sk/form.sb.sef.json
  next/backend/forms/index.ts
  next/jest.config.js
  next/package.json
  next/pages/api/eforms/[id]/transform/html.ts
  next/pages/api/eforms/[id]/transform/text.ts
  next/utils/xslt.ts
  next/yarn.lock
Labels: fix & ship :ship:

#360 FORM-197: Design system shadow
  next/components/ui/Videos/Videos.tsx
  next/tailwind.config.js
Labels: fix & ship :ship:
