Repository bratislava/bratislava.sk, pull requests merged in 2023-01, with the labels that each got.

#446 FORM-200: async validation
  next/__tests__/forms.test.ts
  next/__tests__/utils/forms.test.ts
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/backend/utils/forms.ts
  next/jest.config.js
  next/pages/api/eforms/[id]/submit.ts
  next/pages/api/eforms/[id]/transform/xml.ts
  next/pages/api/eforms/validation.tsx
  next/pages/form/[eform].tsx
  next/utils/api.ts
  next/utils/forms.ts
  next/utils/utils.ts
  next/utils/xslt.ts
Labels: fix & ship :ship:

#479 Form-168/Radio-fix-styling
  next/backend/forms/test/uiSchema.json
  next/components/forms/widget-components/RadioButton/Radio.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
Labels: fix & ship :ship:

#475 Form-171/fix-select
  next/components/forms/widget-components/SelectField/Dropdown.tsx
  next/components/forms/widget-components/SelectField/DropdownRow.tsx
Labels: fix & ship :ship:

#472 FORM-241 zastita primatora form
  next/backend/forms/index.ts
  next/backend/forms/zastitaPrimatora.ts
  next/backend/forms/zastitaPrimatora/data.json
  next/backend/forms/zastitaPrimatora/form.fo.xslt
  next/backend/forms/zastitaPrimatora/form.html.sef.json
  next/backend/forms/zastitaPrimatora/form.html.xslt
  next/backend/forms/zastitaPrimatora/form.sb.sef.json
  next/backend/forms/zastitaPrimatora/form.sb.xslt
  next/backend/forms/zastitaPrimatora/schema.json
  next/backend/forms/zastitaPrimatora/schema.xsd.ts
  next/backend/forms/zastitaPrimatora/uiSchema.json
  next/backend/forms/zastitaPrimatora/xmlTemplate.ts
Labels: fix & ship :ship:

#485 Needed changes for meilisearch
  strapi/kubernetes/base/deployment.yml
  strapi/kubernetes/base/kustomization.yml
  strapi/kubernetes/envs/Dev/kustomization.yml
  strapi/kubernetes/envs/Prod/kustomization.yml
  strapi/kubernetes/envs/Staging/kustomization.yml
Labels: infrastructure

#478 Form-202/Checkbox RJSF fix
  next/backend/forms/test/schema.json
  next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
  next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
Labels: fix & ship :ship:

#486 Form-203/Radio button RJSF error handling
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
Labels: fix & ship :ship:

#496 Form-232/Banner
  next/assets/images/banner-phone.png
  next/components/forms/simple-components/Banner.tsx
  next/components/styleguide/showcases/BannerShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#497 FORM-251 login
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/assets/images/forms/hidden.svg
  next/components/forms/simple-components/Button.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/PasswordField/PasswordField.tsx
  next/components/layouts/LoginRegisterLayout.tsx
  next/components/ui/AccountContainer/AccountContainer.tsx
  next/components/ui/AccountNavBar/AccountNavBar.tsx
  next/components/ui/LoginForm/LoginForm.tsx
  next/package.json
  next/pages/login.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
  next/utils/useAccount.ts
  next/utils/useHookForm.ts
  next/yarn.lock
Labels: fix & ship :ship:

#505 Form-248/Markdown content in accordion
  next/components/forms/simple-components/Accordion.tsx
  next/components/forms/simple-components/Tooltip.tsx
  next/components/styleguide/showcases/AccordionShowCase.tsx
  next/package.json
  next/yarn.lock
Labels: fix & ship :ship:

#494 FORM-188/summary
  next/assets/images/forms/edit_icon.svg
  next/components/forms/steps/Summary/SummaryRow.tsx
  next/components/forms/steps/Summary/TransformedFormData.ts
  next/components/styleguide/showcases/SummaryRowShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#495 Form-183/stepper-view-desktop
  next/components/forms/steps/StepperView.tsx
  next/components/forms/steps/StepperViewRow.tsx
  next/components/forms/types/TransformedFormData.ts
  next/components/styleguide/showcases/StepperShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#507 FORM-256 forgotten password
  next/assets/images/forms/success.svg
  next/components/forms/segments/AccountContainer/AccountContainer.tsx
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/AccountSuccessAlert/AccountSuccessAlert.tsx
  next/components/forms/segments/ForgottenPasswordForm/ForgottenPasswordForm.tsx
  next/components/forms/segments/LoginForm/LoginForm.tsx
  next/components/forms/segments/NewPasswordForm/NewPasswordForm.tsx
  next/components/layouts/LoginRegisterLayout.tsx
  next/pages/forgotten-password.tsx
  next/pages/login.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
  next/utils/string.ts
  next/utils/useAccount.ts
  next/utils/useHookForm.ts
Labels: fix & ship :ship:

#487 FORM-246: Modal background
  next/components/forms/widget-components/Modals/MessageModal.tsx
  next/components/forms/widget-components/Modals/Modal.tsx
Labels: fix & ship :ship:

#480 FORM-247: Updated Field Header
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/info-components/UploadFieldHeader.tsx
  next/components/forms/types/WidgetOptions.ts
  next/components/forms/widget-components/DateTimePicker/DateField.tsx
  next/components/forms/widget-components/DateTimePicker/DatePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/PasswordField/PasswordField.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
  next/components/forms/widget-components/Upload/Upload.tsx
  next/components/forms/widget-wrappers/InputFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/UploadWidgetRJSF.tsx
  next/components/styleguide/showcases/FieldHeaderShowCase.tsx
  next/components/styleguide/showcases/InputFieldShowCase.tsx
  next/package.json
  next/yarn.lock
Labels: fix & ship :ship:

#509 FORM: Fix title line-height
  next/backend/forms/test/uiSchema.json
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/info-components/UploadFieldHeader.tsx
  next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
Labels: fix & ship :ship:

#510 Form-208/rjsf-textarea-fix
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
Labels: fix & ship :ship:

#514 FORM-203: Orientation prop and fix after review
  next/backend/forms/test/uiSchema.json
  next/components/forms/widget-components/RadioButton/Radio.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
Labels: fix & ship :ship:

#512 FORM-183/stepper-view-desktop-fix
  next/components/forms/steps/StepperViewRow.tsx
Labels: fix & ship :ship:

#511 Form-206/select-fix
  next/components/forms/widget-components/SelectField/Dropdown.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
Labels: fix & ship :ship:

#508 Form 249/RJSF markdown in accordion
  next/backend/forms/test/uiSchema.json
  next/components/forms/simple-components/Accordion.tsx
  next/components/forms/types/WidgetOptions.ts
  next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
  next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/InputFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
  next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TextAreaFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/UploadWidgetRJSF.tsx
  next/components/forms/widget-wrappers/WidgetWrapper.tsx
  next/components/styleguide/showcases/AccordionShowCase.tsx
  next/utils/utils.ts
Labels: fix & ship :ship:

#516 Form-178/Fix toggle button
  next/components/forms/simple-components/Toggle.tsx
  next/components/styleguide/showcases/ToggleShowCase.tsx
Labels: needs review :pray:

#529 order properties according to JSON chema (if exists)
  next/backend/forms/kontajneroveStojiska/schema.xsd.ts
  next/backend/utils/forms.ts
Labels: fix & ship :ship:

#515 feat: Added variables to requests resources CPU/Mem
  next/kubernetes/base/deployment.yml
  next/kubernetes/envs/Dev/config.json
  next/kubernetes/envs/Prod/config.json
  next/kubernetes/envs/Staging/config.json
  strapi/kubernetes/base/deployment.yml
  strapi/kubernetes/base/stateful-set-meilisearch.yml
  strapi/kubernetes/base/stateful-set.yml
  strapi/kubernetes/envs/Dev/config.json
  strapi/kubernetes/envs/Prod/config.json
  strapi/kubernetes/envs/Staging/config.json
Labels: fix & ship :ship:, infrastructure

#518 FORM-233: Error handling after review
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
  next/components/forms/widget-components/RadioButton/RadioGroup.tsx
  next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
Labels: fix & ship :ship:

#537 Turn off Sentry
  next/next.config.js
  next/sentry.client.config.js
  next/sentry.server.config.js
Labels: needs review :pray:

#513 Form-240/RJSF-FieldGroups
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/ThemedForm.tsx
  next/components/forms/groups/DateFromTo.tsx
  next/components/forms/groups/DateTimeGroup.tsx
  next/components/forms/groups/DoubledInputField.tsx
  next/components/forms/groups/TimeFromTo.tsx
  next/components/forms/groups/index.ts
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/types/ExplicitOptional.ts
  next/components/forms/types/WidgetOptions.ts
  next/components/forms/widget-components/DateTimePicker/Calendar/CalendarCell.tsx
  next/components/forms/widget-components/DateTimePicker/Calendar/CalendarGrid.tsx
  next/components/forms/widget-components/DateTimePicker/DateField.tsx
  next/components/forms/widget-components/DateTimePicker/DatePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeSelector.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/PasswordField/PasswordField.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
  next/components/forms/widget-wrappers/WidgetWrapper.tsx
  next/components/forms/widget-wrappers/fieldGroupsRJSF/DateFromToWidgetRJSF.tsx
  next/components/forms/widget-wrappers/fieldGroupsRJSF/DateTimeWidgetRJSF.tsx
  next/components/forms/widget-wrappers/fieldGroupsRJSF/DoubledInputWidgetFieldRJSF.tsx
  next/components/forms/widget-wrappers/fieldGroupsRJSF/TimeFromToWidgetRJSF.tsx
  next/pages/form/[eform].tsx
Labels: fix & ship :ship:

#543 FORM-270: Implement react-hook-form warning
  next/.eslintrc.js
Labels: fix & ship :ship:

#535 FORM-229: Update formular schema
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/data.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.fo.xslt
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.html.sef.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.html.xslt
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.sb.sef.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.sb.xslt
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/schema.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/schema.xsd.ts
Labels: fix & ship :ship:

#530 FORM-270: Page structure - mestske konto
  next/assets/images/account/business-icon.svg
  next/assets/images/account/help-icon.svg
  next/assets/images/account/home-icon.svg
  next/assets/images/account/payment-icon.svg
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/AccountSectionHeader/AccountSectionHeader.tsx
  next/components/forms/segments/AccountSections/HelpSection/HelpSection.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/next.config.js
  next/pages/account/i-have-a-problem.tsx
  next/pages/account/intro.tsx
  next/pages/account/municipal-services.tsx
  next/pages/account/taxes-and-fees.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#545 FORM-261 zmena korešpondenčnej adresy
  next/components/forms/segments/CorrespondenceAddressForm/CorrespondenceAddressForm.tsx
  next/components/forms/segments/CorrespondenceAddressModal/CorrespondenceAddressModal.tsx
  next/components/forms/widget-components/Modals/Modal.tsx
  next/components/styleguide/showcases/ModalShowCase.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
  next/utils/useHookForm.ts
Labels: fix & ship :ship:
