Repository bratislava/bratislava.sk, pull requests merged in 2023-02, with the labels that each got.

#544 Form-230/Tile component
  next/assets/images/circle-arrow-right.svg
  next/assets/images/container-logo.svg
  next/assets/images/investment-logo.svg
  next/assets/images/property-tax-logo.svg
  next/assets/images/swimming-pools-logo.svg
  next/components/forms/icon-components/ContainerLogoIcon.tsx
  next/components/forms/icon-components/InvestmentLogoIcon.tsx
  next/components/forms/icon-components/PropertyTaxLogoIcon.tsx
  next/components/forms/icon-components/SwimmingPoolsLogoIcon.tsx
  next/components/forms/info-components/Alert.tsx
  next/components/forms/simple-components/Accordion.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/forms/simple-components/ProgressBar.tsx
  next/components/forms/simple-components/ServiceCard.tsx
  next/components/forms/simple-components/Toggle.tsx
  next/components/forms/widget-components/Checkbox/SingleCheckbox.tsx
  next/components/forms/widget-components/Modals/MessageModal.tsx
  next/components/forms/widget-components/Modals/Modal.tsx
  next/components/forms/widget-components/RadioButton/Radio.tsx
  next/components/styleguide/showcases/ServiceCardShowCase.tsx
  next/pages/styleguide.tsx
Labels: fix & ship :ship:

#547 Form 257/my profile
  next/assets/images/forms/edit_white.svg
  next/assets/images/forms/lock-white.svg
  next/components/forms/simple-components/Toggle.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/Modals/MessageModal.tsx
  next/components/layouts/TestUserProfileLayout.tsx
  next/components/ui/UserProfile/UserConsent.tsx
  next/components/ui/UserProfile/UserProfileConsents.tsx
  next/components/ui/UserProfile/UserProfileDetail.tsx
  next/components/ui/UserProfile/UserProfileDetailEdit.tsx
  next/components/ui/UserProfile/UserProfileDetailView.tsx
  next/components/ui/UserProfile/UserProfileDetailViewRow.tsx
  next/components/ui/UserProfile/UserProfileDetailsButtons.tsx
  next/components/ui/UserProfile/UserProfilePassword.tsx
  next/components/ui/UserProfile/UserProfilePhoto.tsx
  next/components/ui/UserProfile/UserProfileSection.tsx
  next/components/ui/UserProfile/UserProfileSectionHeader.tsx
  next/components/ui/UserProfile/UserProfileView.tsx
  next/pages/user-profile.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
  next/utils/useAccount.ts
Labels: fix & ship :ship:

#546 FORM/fields-styles-update
  next/assets/images/forms/icon-help.svg
  next/components/forms/info-components/FieldErrorMessage.tsx
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/simple-components/Tag.tsx
  next/components/forms/widget-components/DateTimePicker/Calendar/CalendarGrid.tsx
  next/components/forms/widget-components/DateTimePicker/DateField.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/DropdownRow.tsx
  next/components/forms/widget-components/SelectField/SelectAllDropdownRow.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/SelectField/SelectFieldBox.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
Labels: fix & ship :ship:

#476 FORM-229: Formular Zavazne stanovisko
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/data.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.fo.xslt
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.html.sef.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.html.xslt
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.sb.sef.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/form.sb.xslt
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/schema.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/schema.xsd.ts
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/uiSchema.json
  next/backend/forms/zavazneStanoviskoKInvesticnejCinnosti/xmlTemplate.ts
  next/components/forms/groups/DateFromTo.tsx
  next/components/forms/groups/DateTimeGroup.tsx
  next/components/forms/groups/DoubledInputField.tsx
  next/components/forms/groups/TimeFromTo.tsx
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/info-components/UploadFieldHeader.tsx
  next/components/forms/segments/CorrespondenceAddressForm/CorrespondenceAddressForm.tsx
  next/components/forms/segments/IdentityVerificationForm/IdentityVerificationForm.tsx
  next/components/forms/segments/RegisterForm/RegisterForm.tsx
  next/components/forms/templates/ObjectFieldTemplate.tsx
  next/components/forms/types/WidgetOptions.ts
  next/components/forms/widget-components/DateTimePicker/DateField.tsx
  next/components/forms/widget-components/DateTimePicker/DatePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/PasswordField/PasswordField.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
  next/components/forms/widget-components/Upload/Upload.tsx
  next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/InputFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TextAreaFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/UploadWidgetRJSF.tsx
  next/components/styleguide/showcases/DatePickerShowCase.tsx
  next/components/styleguide/showcases/FieldHeaderShowCase.tsx
  next/components/styleguide/showcases/InputFieldShowCase.tsx
  next/components/styleguide/showcases/SearchFieldShowCase.tsx
  next/components/styleguide/showcases/SelectFieldShowCase.tsx
  next/components/styleguide/showcases/TextAreaFieldShowCase.tsx
  next/components/styleguide/showcases/TimePickerShowCase.tsx
  next/pages/form/[eform].tsx
Labels: fix & ship :ship:

#519 FORM-262: Dane a poplatky - visual
  next/assets/images/forms/exclamation-icon.svg
  next/assets/images/forms/warning-time-icon.svg
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCard.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
Labels: fix & ship :ship:

#551 BA-687 add chatbot to page
  next/assets/images/message.svg
  next/components/molecules/chat.tsx
  next/package.json
  next/pages/_app.tsx
  next/pages/bratislava.css
  next/yarn.lock
Labels: fix & ship :ship:

#569 FORM-288 change email verification label
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#563 FORM-276: Grammatical mistakes
  next/components/forms/info-components/FieldErrorMessage.tsx
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#564 FORM-280: Fix icon in PasswordField
  next/components/forms/widget-components/PasswordField/PasswordField.tsx
Labels: fix & ship :ship:

#565 FORM-282: Fix names of inputs on register page
  next/components/forms/segments/RegisterForm/RegisterForm.tsx
Labels: fix & ship :ship:

#566 FORM-283: Fix fields and buttons style and spacing
  next/components/forms/segments/EmailVerificationForm/EmailVerificationForm.tsx
  next/components/forms/segments/ForgottenPasswordForm/ForgottenPasswordForm.tsx
  next/components/forms/segments/IdentityVerificationForm/IdentityVerificationForm.tsx
  next/components/forms/segments/LoginForm/LoginForm.tsx
  next/components/forms/segments/NewPasswordForm/NewPasswordForm.tsx
  next/components/forms/segments/PasswordChangeForm/PasswordChangeForm.tsx
  next/components/forms/segments/RegisterForm/RegisterForm.tsx
  next/components/forms/simple-components/Button.tsx
  next/components/forms/types/WidgetOptions.ts
  next/components/forms/widget-components/Checkbox/SingleCheckbox.tsx
  next/components/forms/widget-wrappers/WidgetWrapper.tsx
Labels: fix & ship :ship:

#570 FORM: Update typography
  next/components/forms/info-components/Alert.tsx
  next/components/forms/info-components/FieldErrorMessage.tsx
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/info-components/UploadFieldHeader.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCard.tsx
  next/components/forms/simple-components/Accordion.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/forms/simple-components/Button.tsx
  next/components/forms/simple-components/ProgressBar.tsx
  next/components/forms/simple-components/ServiceCard.tsx
  next/components/forms/simple-components/Tag.tsx
  next/components/forms/simple-components/Toggle.tsx
  next/components/forms/widget-components/Checkbox/Checkbox.tsx
  next/components/forms/widget-components/Checkbox/CheckboxGroup.tsx
  next/components/forms/widget-components/Checkbox/SingleCheckbox.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/Modals/MessageModal.tsx
  next/components/forms/widget-components/Modals/Modal.tsx
  next/components/forms/widget-components/RadioButton/Radio.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/DropdownRow.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
  next/components/forms/widget-components/Upload/UploadButton.tsx
  next/components/forms/widget-components/Upload/UploadDropArea.tsx
  next/pages/typography.css
  next/tailwind.config.js
Labels: fix & ship :ship:

#567 FORM-234 header
  next/assets/images/account/help-filled.svg
  next/assets/images/account/logout.svg
  next/assets/images/account/profile-outlined.svg
  next/assets/images/account/profile.svg
  next/assets/images/account/volume.svg
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/HambergerMenu/HamburgerMenu.tsx
  next/components/forms/segments/LoginRegisterNavBar/LoginRegisterNavBar.tsx
  next/components/forms/simple-components/Menu/Menu.tsx
  next/components/forms/simple-components/Menu/MenuButton.tsx
  next/components/forms/simple-components/Menu/MenuContainer.tsx
  next/components/forms/simple-components/Menu/MenuItem.tsx
  next/components/forms/simple-components/Menu/MenuPopover.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/components/layouts/LoginRegisterLayout.tsx
  next/components/layouts/TestUserProfileLayout.tsx
  next/pages/forgotten-password.tsx
  next/pages/password-change.tsx
  next/pages/register.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
  next/utils/useAccount.ts
Labels: fix & ship :ship:

#582 FORM-285 identity verification
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/components/forms/segments/EmailVerificationForm/EmailVerificationForm.tsx
  next/components/forms/segments/ForgottenPasswordForm/ForgottenPasswordForm.tsx
  next/components/forms/segments/IdentityVerificationForm/IdentityVerificationForm.tsx
  next/components/forms/segments/LoginForm/LoginForm.tsx
  next/components/forms/segments/NewPasswordForm/NewPasswordForm.tsx
  next/components/forms/segments/PasswordChangeForm/PasswordChangeForm.tsx
  next/components/forms/segments/RegisterForm/RegisterForm.tsx
  next/components/ui/ForgottenPasswordForm/ForgottenPasswordForm.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
  next/utils/api.ts
  next/utils/useAccount.ts
Labels: fix & ship :ship:

#585 FORM-278 bach button
  next/components/layouts/LoginRegisterLayout.tsx
  next/pages/forgotten-password.tsx
  next/pages/password-change.tsx
  next/pages/register.tsx
Labels: fix & ship :ship:

#586 FORM-284 account navigation
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/pages/account/index.tsx
Labels: fix & ship :ship:

#587 FORM-287 verification
  next/components/forms/segments/EmailVerificationForm/EmailVerificationForm.tsx
  next/pages/login.tsx
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#571 FORM-275: Update Tooltip
  next/assets/images/forms/icon-help.svg
  next/assets/images/forms/tooltip-horizontal-arrow.svg
  next/assets/images/forms/tooltip-vertical-arrow.svg
  next/components/forms/info-components/FieldHeader.tsx
  next/components/forms/info-components/Tooltip.tsx
  next/components/forms/info-components/Tooltip/Tooltip.tsx
  next/components/forms/info-components/Tooltip/TooltipPopup.tsx
  next/components/forms/simple-components/Accordion.tsx
  next/components/forms/simple-components/Tooltip.tsx
  next/components/forms/widget-components/Checkbox/Checkbox.tsx
  next/components/forms/widget-components/Checkbox/SingleCheckbox.tsx
  next/components/forms/widget-components/RadioButton/Radio.tsx
  next/components/styleguide/showcases/TooltipShowCase.tsx
Labels: fix & ship :ship:

#588 Form-259/TaxHeaderContactInfo_Visual
  next/assets/images/account/file_download.svg
  next/assets/images/chevron-left-2.svg
  next/components/forms/segments/AccountSectionHeader/TaxFeeSectionHeader.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/ContactInformation.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCard.tsx
  next/components/forms/steps/Summary/SummaryRow.tsx
  next/pages/account/taxes-and-fees/[id].tsx
  next/pages/account/taxes-and-fees/index.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#589 Form-264/TaxDetails_Visual
  next/components/forms/icon-components/ExpandMoreIcon.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxDetails.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
  next/components/forms/simple-components/Accordion.tsx
  next/components/styleguide/showcases/AccordionShowCase.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#583 FORM-233: Fix test formular required error
  next/backend/forms/test/schema.json
Labels: fix & ship :ship:

#562 FORM-262: Add waiting and error cards
  next/assets/images/account/mestske-konto-situacia-1-1.svg
  next/assets/images/account/mestske-konto-situacia-2-1.svg
  next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesErrorCard.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesWaitingCard.tsx
  next/components/forms/simple-components/Accordion.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#592 FORM-296: Account Intro page
  next/components/forms/segments/AccountSectionHeader/AccountSectionHeader.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#593 FORM-230: Update service cards
  next/assets/images/account/basket-service-icon.svg
  next/assets/images/account/compass-service-icon.svg
  next/assets/images/account/money-service-icon.svg
  next/assets/images/account/pool-service-icon.svg
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/simple-components/ServiceCard.tsx
  next/components/styleguide/showcases/ServiceCardShowCase.tsx
Labels: fix & ship :ship:

#595 FORM-232: Update Banner component
  next/components/forms/simple-components/Banner.tsx
Labels: fix & ship :ship:

#597 FORM-256 change button label
  next/components/forms/segments/NewPasswordForm/NewPasswordForm.tsx
  next/components/forms/segments/PasswordChangeForm/PasswordChangeForm.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#598 FORM-289: Add Actual section
  next/components/forms/segments/AccountSections/IntroSection/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#596 FORM-285 fix rc tooltip, validation
  next/components/forms/info-components/Tooltip/TooltipPopup.tsx
  next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
  next/components/forms/segments/AccountSuccessAlert/AccountSuccessAlert.tsx
  next/components/forms/segments/CorrespondenceAddressForm/CorrespondenceAddressForm.tsx
  next/components/forms/segments/EmailVerificationForm/EmailVerificationForm.tsx
  next/components/forms/segments/IdentityVerificationForm/IdentityVerificationForm.tsx
  next/components/forms/segments/MigrationForm/MigrationForm.tsx
  next/components/forms/segments/NewPasswordForm/NewPasswordForm.tsx
  next/pages/register.tsx
  next/public/locales/sk/account.json
  next/utils/useHookForm.ts
Labels: fix & ship :ship:

#493 Form 183/stepper
  next/backend/forms/test/schema.json
  next/backend/forms/test/uiSchema.json
  next/components/forms/simple-components/Button.tsx
  next/components/forms/steps/FinalStep.tsx
  next/components/forms/steps/Summary/Summary.tsx
  next/components/forms/steps/Summary/SummaryMessages.tsx
  next/components/forms/steps/Summary/SummaryStep.tsx
  next/components/forms/widget-wrappers/CheckboxWidgetRJSF.tsx
  next/components/forms/widget-wrappers/DatePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/ExampleInput.tsx
  next/components/forms/widget-wrappers/InputFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/RadioButtonWidgetRJSF.tsx
  next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TextAreaFieldWidgetRJSF.tsx
  next/components/forms/widget-wrappers/TimePickerWidgetRJSF.tsx
  next/components/forms/widget-wrappers/UploadWidgetRJSF.tsx
  next/components/styleguide/showcases/SummaryRowShowCase.tsx
  next/components/ui/FormRJSF/GeneratedFormRJSF.tsx
  next/pages/_app.tsx
  next/pages/form/[eform].tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
  next/utils/forms.ts
  next/utils/rjsf-schema-handler.ts
Labels: fix & ship :ship:

#594 BA-756 show chatbot only on ukrainian pages
  next/pages/_app.tsx
Labels: fix & ship :ship:

#605 display modal in front of header
  next/components/forms/widget-components/Modals/Modal.tsx
Labels: fix & ship :ship:

#604 fix position of menu popover
  next/components/forms/simple-components/Menu/MenuPopover.tsx
Labels: fix & ship :ship:

#606 FORM-234 fix hamburger menu selection
  next/components/forms/segments/HambergerMenu/HamburgerMenu.tsx
Labels: fix & ship :ship:

#611 FORM-250 fix register
  next/components/forms/segments/RegisterForm/RegisterForm.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/PasswordField/PasswordField.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/pages/login.tsx
  next/pages/register.tsx
  next/utils/constants.tsx
  next/utils/useHookForm.ts
Labels: fix & ship :ship:

#609 FORM-262: Fix font size in TaxesFeesErrorCard
  next/components/forms/segments/AccountMarkdown/AccountMarkdown.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: fix & ship :ship:

#613 Form-306/stepper-mobile
  next/components/forms/steps/FinalStep.tsx
  next/components/forms/steps/StepperView.tsx
  next/components/forms/steps/StepperViewList.tsx
  next/components/forms/steps/StepperViewRow.tsx
  next/components/forms/steps/Summary/Summary.tsx
  next/components/styleguide/showcases/StepperShowCase.tsx
  next/components/ui/FormRJSF/GeneratedFormRJSF.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
  next/utils/rjsf-schema-handler.ts
Labels: fix & ship :ship:

#625 FORM-285 remove slash in RC before api call, reset error
  next/utils/useAccount.ts
Labels: PR: fix & ship :ship:

#624 FORM-234 fix disappearing of parent scrollbar on opened popover
  next/components/forms/simple-components/Menu/Menu.tsx
  next/components/forms/simple-components/Menu/MenuPopover.tsx
Labels: PR: fix & ship :ship:

#622 Form-317/FieldGroups_Zjednotenie
  next/components/forms/groups/DateFromTo.tsx
  next/components/forms/groups/TimeFromTo.tsx
Labels: PR: fix & ship :ship:, bug

#626 FORM-284 add menu links
  next/components/layouts/AccountPageLayout.tsx
Labels: pr: fix & ship :ship:

#646 FORM-334: update address in cognito
  next/components/forms/segments/AccountSections/TaxesFeesSection/ContactInformation.tsx
  next/components/forms/segments/CorrespondenceAddressForm/CorrespondenceAddressForm.tsx
  next/components/forms/segments/CorrespondenceAddressModal/CorrespondenceAddressModal.tsx
  next/components/styleguide/showcases/ModalShowCase.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
  next/utils/useAccount.ts
Labels: pr: fix & ship :ship:

#639 FORM-285 process new error names
  next/pages/register.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
  next/utils/api.ts
Labels: pr: fix & ship :ship:

#651 FORM-314 marketing subscribe
  next/components/forms/segments/RegisterForm/RegisterForm.tsx
  next/utils/api.ts
  next/utils/useAccount.ts
Labels: pr: fix & ship :ship:

#608 FORM-213: Design system - breakpoints
  next/components/atoms/BlogCard.tsx
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/AccountSectionHeader/AccountSectionHeader.tsx
  next/components/forms/segments/AccountSections/IntroSection/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesErrorCard.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesWaitingCard.tsx
  next/components/forms/segments/LoginRegisterNavBar/LoginRegisterNavBar.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/molecules/Footer.tsx
  next/components/molecules/sections/documentList/DocumentListModalBody.tsx
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/BAStickyMenu/BAStickyMenu.tsx
  next/components/ui/BAStickyMenu/MenuPanel.tsx
  next/components/ui/BlogCard/BlogCard.tsx
  next/components/ui/Carousel/Carousel.tsx
  next/components/ui/Footer/Footer.tsx
  next/components/ui/NewsLetter/NewsLetter.tsx
  next/components/ui/NumericalListSection/NumericalListSection.tsx
  next/components/ui/SectionContainer/SectionContainer.tsx
  next/package.json
  next/pages/index.css
  next/tailwind.config.js
  next/yarn.lock
Labels: pr: fix & ship :ship:

#616 FORM-289: Fix Aktualne Section after review
  next/components/forms/segments/AccountSections/IntroSection/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/simple-components/ServiceCard.tsx
  next/public/Img/platba_dane2.png
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#612 FORM-296: Fix Intro page after review
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/styleguide/StyleGuideWrapper.tsx
Labels: pr: fix & ship :ship:

#620 FORM-245: Registration Modal
  next/assets/images/forms/close.svg
  next/assets/images/forms/selected-dark.svg
  next/components/forms/segments/RegistrationModal/RegistrationModal.tsx
  next/components/styleguide/showcases/ModalShowCase.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#621 Form-302/Modal phone number
  next/components/forms/segments/PhoneNumberForm/PhoneNumberForm.tsx
  next/components/forms/segments/PhoneNumberModal/PhoneNumberModal.tsx
  next/components/forms/widget-components/Modals/Modal.tsx
  next/components/styleguide/showcases/ModalShowCase.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/account.json
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#619 Form 259 264 container fix
  next/components/forms/segments/AccountModal/AccountModal.tsx
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/AccountSectionHeader/TaxFeeSectionHeader.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/ContactInformation.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxDetails.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
  next/components/forms/segments/CorrespondenceAddressModal/CorrespondenceAddressModal.tsx
  next/components/forms/simple-components/AccordionTableContent.tsx
  next/components/forms/steps/Summary/SummaryRow.tsx
  next/components/forms/widget-components/Modals/Modal.tsx
  next/components/styleguide/showcases/AccordionShowCase.tsx
  next/pages/index.css
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:
