Repository bratislava/bratislava.sk, pull requests merged in 2023-03, with the labels that each got.

#652 Form-333/SafariPasswordField
  next/pages/bratislava.css
Labels: pr: fix & ship :ship:

#653 FORM-335 account provider
  next/pages/_app.tsx
  next/utils/useAccount.tsx
Labels: pr: fix & ship :ship:

#618 FORM-298: Mam problem Section
  next/components/forms/segments/AccountSections/HelpSection/HelpSection.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/forms/simple-components/Button.tsx
Labels: pr: fix & ship :ship:

#645 FORM-297: Municipal Service section
  next/assets/images/account/municipal-services/basket-icon.svg
  next/assets/images/account/municipal-services/christmas-tree-icon.svg
  next/assets/images/account/municipal-services/city-tree-icon.svg
  next/assets/images/account/municipal-services/compass-icon.svg
  next/assets/images/account/municipal-services/excavations-icon.svg
  next/assets/images/account/municipal-services/front-gardens-icon.svg
  next/assets/images/account/municipal-services/gardens-icon.svg
  next/assets/images/account/municipal-services/library-icon.svg
  next/assets/images/account/municipal-services/marinium-icon.svg
  next/assets/images/account/municipal-services/money-icon.svg
  next/assets/images/account/municipal-services/mosquito-icon.svg
  next/assets/images/account/municipal-services/parking-icon.svg
  next/assets/images/account/municipal-services/pool-icon.svg
  next/assets/images/account/municipal-services/security-icon.svg
  next/assets/images/account/municipal-services/sewerage-icon.svg
  next/assets/images/account/municipal-services/taxes-icon.svg
  next/assets/images/account/municipal-services/theatre-icon.svg
  next/assets/images/account/municipal-services/tow-icon.svg
  next/assets/images/account/municipal-services/transport-icon.svg
  next/assets/images/account/municipal-services/tree-icon.svg
  next/assets/images/account/municipal-services/zoo-icon.svg
  next/components/forms/segments/AccountSectionHeader/MunicipalServicesSectionHeader.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/components/styleguide/showcases/ServiceCardShowCase.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#661 Form-230/FixStyleguideIcons
  next/components/styleguide/showcases/ServiceCardShowCase.tsx
Labels: pr: fix & ship :ship:

#659 FORM: Update Banner component on account page
  next/assets/images/forms/call.svg
  next/components/forms/segments/AccountSections/HelpSection/HelpSection.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/forms/simple-components/Button.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#666 FORM-316: Modal skip step visual
  next/assets/images/forms/close-thin.svg
  next/assets/images/forms/error-icon.svg
  next/components/forms/segments/SkipStepModal/SkipStepModal.tsx
  next/components/styleguide/showcases/ModalShowCase.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
Labels: pr: needs review :pray:

#663 Remove unused content types and rename others to slovak
  next/graphql/index.ts
  strapi/README.md
  strapi/patches/@strapi+plugin-users-permissions+4.6.0.patch
  strapi/src/api/audience/content-types/audience/schema.json
  strapi/src/api/audience/controllers/audience.js
  strapi/src/api/audience/routes/audience.js
  strapi/src/api/audience/services/audience.js
  strapi/src/api/author/content-types/author/schema.json
  strapi/src/api/author/controllers/author.js
  strapi/src/api/author/routes/author.js
  strapi/src/api/author/services/author.js
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/src/api/form/content-types/form/schema.json
  strapi/src/api/form/controllers/form.js
  strapi/src/api/form/routes/form.js
  strapi/src/api/form/services/form.js
  strapi/src/api/menu/content-types/menu/schema.json
  strapi/src/api/menu/controllers/menu.js
  strapi/src/api/menu/routes/menu.js
  strapi/src/api/menu/services/menu.js
  strapi/src/api/page-category/content-types/page-category/schema.json
  strapi/src/api/page-subcategory/content-types/page-subcategory/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/tag/content-types/tag/schema.json
  strapi/src/components/menu/menu-item.json
  strapi/src/components/menu/menu-section.json
Labels: pr: fix & ship :ship:

#656 reset rc
  next/pages/get-jwt.tsx
  next/utils/api.ts
  next/utils/useAccount.tsx
Labels: pr: fix & ship :ship:

#655 Form-324/Modal_phoneNumber_functionality
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/IdentityVerificationForm/IdentityVerificationForm.tsx
  next/components/forms/segments/PhoneNumberForm/PhoneNumberForm.tsx
  next/components/forms/segments/PhoneNumberModal/PhoneNumberModal.tsx
  next/components/styleguide/showcases/ModalShowCase.tsx
  next/pages/register.tsx
Labels: pr: fix & ship :ship:

#654 Form-264/TaxDetailsFix_Visual
  next/assets/images/account/payment-icon.svg
  next/components/forms/segments/AccountSectionHeader/TaxFeeSectionHeader.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxDetails.tsx
  next/components/forms/simple-components/AccordionTableContent.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#668 Feature/#637 add map road closures
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/LoginRegisterNavBar/LoginRegisterNavBar.tsx
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/Iframe/Iframe.tsx
  next/components/ui/RentReservationForm/RentReservationForm.tsx
  next/components/ui/Sections/Posts/Posts.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/utils/utils.ts
Labels: pr: fix & ship :ship:

#665 Feature/#642 skip to content
  bratislava.sk.code-workspace
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/segments/LoginRegisterNavBar/LoginRegisterNavBar.tsx
  next/components/layouts/BasePageLayout.tsx
  next/components/layouts/HomepagePageLayout.tsx
  next/components/molecules/NavBar.tsx
  next/components/molecules/SkipToContentButton.tsx
  next/components/sections/WithoutStickyMenuSection.tsx
  next/components/sections/useWithoutStickyMenuSection.ts
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/Bookmarks/Bookmarks.tsx
  next/components/ui/PageHeader/PageHeader.tsx
  next/pages/index.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/tailwind.config.js
  next/utils/utils.ts
Labels: pr: fix & ship :ship:

#685 Sections cleanup
  next/components/molecules/OrganizationalStructure/OrganizationalStructure.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/News.tsx
  next/components/molecules/sections/general/AccordionSection.tsx
  next/components/molecules/sections/general/ArticlesListSection/ArticlesList.tsx
  next/components/molecules/sections/general/ArticlesListSection/ArticlesListSection.tsx
  next/components/molecules/sections/general/CalculatorSection/CalculatorSection.tsx
  next/components/molecules/sections/general/CalculatorSection/MinimumCalculator.tsx
  next/components/molecules/sections/general/ColumnedTextSection.tsx
  next/components/molecules/sections/general/ContactSection.tsx
  next/components/molecules/sections/general/DividerSection.tsx
  next/components/molecules/sections/general/DocumentListSection/DocumentListModalBody.tsx
  next/components/molecules/sections/general/DocumentListSection/DocumentListResults.tsx
  next/components/molecules/sections/general/DocumentListSection/DocumentListSection.tsx
  next/components/molecules/sections/general/FileListSection.tsx
  next/components/molecules/sections/general/GallerySection.tsx
  next/components/molecules/sections/general/IconTitleDescSection.tsx
  next/components/molecules/sections/general/IframeSection.tsx
  next/components/molecules/sections/general/LinksSection.tsx
  next/components/molecules/sections/general/ListItemsSection.tsx
  next/components/molecules/sections/general/NarrowTextSection.tsx
  next/components/molecules/sections/general/NewsletterSection.tsx
  next/components/molecules/sections/general/NumericalListSection.tsx
  next/components/molecules/sections/general/OrganizationalStructureSection.tsx
  next/components/molecules/sections/general/TextWithImageSection.tsx
  next/components/molecules/sections/general/VideosSection.tsx
  next/components/molecules/sections/general/WavesSection.tsx
  next/components/molecules/sections/homepage/BlogCards.tsx
  next/components/molecules/sections/homepage/PrimatorCouncil.tsx
  next/components/ui/Iframe/Iframe.tsx
  next/components/ui/NarrowText/NarrowText.tsx
  next/components/ui/NumericalList/NumericalList.tsx
  next/components/ui/NumericalListItem/NumericalListItem.tsx
  next/components/ui/NumericalListSectionUI/NumericalListSectionUI.stories.mdx
  next/components/ui/NumericalListSectionUI/NumericalListSectionUI.tsx
  next/components/ui/Rent/Rent.tsx
  next/components/ui/Sections/RentBenefits/RentBenefits.tsx
  next/components/ui/Videos/Videos.tsx
  next/components/ui/Videos/VideosService.ts
  next/components/ui/index.ts
  next/graphql/index.ts
  next/graphql/queries/BlogPosts.graphql
  next/graphql/queries/General.graphql
  next/graphql/queries/Pages.graphql
  next/graphql/queries/Sections.graphql
  next/graphql/queries/Vzn.graphql
  next/package.json
  next/pages/[...slug].tsx
  next/pages/blog/[slug].tsx
  next/pages/form/[eform].tsx
  next/pages/index.tsx
  next/pages/mesto-bratislava/transparentne-mesto/uradna-tabula.tsx
  next/pages/vyhladavanie.tsx
  next/utils/page.ts
  next/yarn.lock
  strapi/package.json
Labels: pr: fix & ship :ship:

#531 BA-670: Adjust quote markdown design
  next/components/atoms/HomepageMarkdown.tsx
Labels: pr: fix & ship :ship:

#669 FORM-293: change label of submit button
  next/components/forms/segments/NewPasswordForm/NewPasswordForm.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#670 Form-333/SafariPasswordFieldFix_StrongPassword
  next/pages/bratislava.css
Labels: pr: fix & ship :ship:

#671 Form-302/Fix_PhoneNumber_Modal_Visual
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/segments/PhoneNumberForm/PhoneNumberForm.tsx
  next/components/forms/segments/PhoneNumberModal/PhoneNumberModal.tsx
  next/public/locales/en/account.json
  next/public/locales/en/forms.json
  next/public/locales/sk/account.json
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#684 FORM-296: Fix banner styles
  next/components/forms/simple-components/Banner.tsx
Labels: pr: fix & ship :ship:

#590 Form-266/PaymentData_Footer_Visual
  next/assets/images/content_copy.svg
  next/components/forms/segments/AccountSections/TaxesFeesSection/PaymentData.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFeeSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxFooter.tsx
  next/components/forms/simple-components/ClipboardCopy.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#667 FORM-320: Modal Skip Step - logic
  next/components/forms/segments/SkipStepModal/SkipStepModal.tsx
  next/components/ui/FormRJSF/GeneratedFormRJSF.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#693 Fix_PhoneNumberFormDOMWarning
  next/components/forms/segments/PhoneNumberForm/PhoneNumberForm.tsx
Labels: pr: fix & ship :ship:

#691 Form-338/CapitalLetter
  next/components/forms/widget-components/InputField/InputField.tsx
Labels: pr: fix & ship :ship:

#692 Form 257/my profile
  next/components/forms/simple-components/Button.tsx
  next/components/ui/UserProfile/UserProfileDetail.tsx
  next/components/ui/UserProfile/UserProfileDetailEdit.tsx
  next/components/ui/UserProfile/UserProfileDetailsButtons.tsx
  next/components/ui/UserProfile/UserProfileView.tsx
  next/package.json
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
  next/utils/useAccount.tsx
  next/yarn.lock
Labels: pr: fix & ship :ship:

#706 fix undefined estimatedTotalHits
  next/components/molecules/sections/general/DocumentListSection/DocumentListResults.tsx
Labels: pr: fix & ship :ship:

#698 Official board
  next/backend/services/ginis.ts
  next/components/molecules/Sections.tsx
  next/components/molecules/chat.tsx
  next/components/molecules/sections/general/OfficialBoardSection/OfficialBoardSection.tsx
  next/components/providers/BAQueryClientProvider.tsx
  next/graphql/index.ts
  next/graphql/queries/Sections.graphql
  next/package.json
  next/pages/_app.tsx
  next/pages/api/ginis/documents-list.ts
  next/yarn.lock
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/official-board.json
Labels: pr: fix & ship :ship:

#702 Form-329/SuccessScreen_Form
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouFormSection.tsx
  next/pages/form/thank-you.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#710 Update packages
  next/components/atoms/BlogCard.tsx
  next/components/forms/segments/AccountSections/IntroSection/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesCard.tsx
  next/components/forms/segments/HambergerMenu/HamburgerMenu.tsx
  next/components/forms/segments/RegistrationModal/RegistrationModal.tsx
  next/components/forms/simple-components/Banner.tsx
  next/components/forms/simple-components/MLink.tsx
  next/components/forms/simple-components/ServiceCard.tsx
  next/components/layouts/BasePageLayout.tsx
  next/components/layouts/HomepagePageLayout.tsx
  next/components/layouts/LoginRegisterLayout.tsx
  next/components/layouts/TestUserProfileLayout.tsx
  next/components/molecules/HomePageSearchResults.tsx
  next/components/molecules/sections/general/GallerySection.tsx
  next/components/organisms/CookieConsent.tsx
  next/components/styleguide/StyleGuideWrapper.tsx
  next/components/ui/Footer/Footer.tsx
  next/graphql/index.ts
  next/graphql/queries/Pages.graphql
  next/next-i18next.config.js
  next/next.config.js
  next/package.json
  next/pages/404.tsx
  next/pages/[...slug].tsx
  next/pages/_app.tsx
  next/pages/blog/[slug].tsx
  next/pages/bratislava.css
  next/pages/cognito.tsx
  next/pages/get-jwt.tsx
  next/pages/index.css
  next/postcss.config.js
  next/tailwind.config.js
  next/utils/constants.tsx
  next/utils/utils.ts
  next/yarn.lock
Labels: pr: needs review :pray:

#715 Form 257/my profile
  next/components/ui/UserProfile/UserProfileConsents.tsx
  next/components/ui/UserProfile/UserProfileDetail.tsx
  next/components/ui/UserProfile/UserProfileDetailEdit.tsx
  next/components/ui/UserProfile/UserProfileDetailViewRow.tsx
  next/components/ui/UserProfile/UserProfileDetailsButtons.tsx
  next/components/ui/UserProfile/UserProfilePhoto.tsx
  next/components/ui/UserProfile/UserProfileSection.tsx
  next/components/ui/UserProfile/UserProfileSectionHeader.tsx
  next/components/ui/UserProfile/UserProfileView.tsx
  next/pages/user-profile.tsx
Labels: pr: fix & ship :ship:

#711 FORM-340 reset account status on signout
  next/utils/useAccount.tsx
Labels: pr: fix & ship :ship:

#709 FORM-339 navbar
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/layouts/AccountPageLayout.tsx
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#694 Form-289/Safari_IconFix
  next/components/forms/segments/AccountSections/IntroSection/AnnouncementBlock.tsx
  next/components/forms/segments/RegistrationModal/RegistrationModal.tsx
  next/components/forms/simple-components/Button.tsx
Labels: pr: fix & ship :ship:

#718 FORM-292: Login & Register - activate account component
  next/components/forms/segments/AccountActivator/AccountActivator.tsx
  next/components/forms/segments/AccountContainer/AccountContainer.tsx
  next/components/layouts/LoginRegisterLayout.tsx
  next/pages/login.tsx
  next/pages/register.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#712 FORM-285 close tooltip on click outside
  next/components/forms/info-components/Tooltip/Tooltip.tsx
Labels: pr: fix & ship :ship:

#708 Form-338/CapitalizeLetter
  next/components/forms/segments/CorrespondenceAddressForm/CorrespondenceAddressForm.tsx
  next/components/forms/segments/RegisterForm/RegisterForm.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/ui/UserProfile/UserProfileDetailEdit.tsx
Labels: pr: fix & ship :ship:

#724 FORM-296: Uvod - fix images and change service cards
  next/assets/images/platba-dane2.png
  next/components/forms/segments/AccountSections/IntroSection/AnnouncementBlock.tsx
  next/components/forms/segments/AccountSections/IntroSection/IntroSection.tsx
  next/components/forms/simple-components/Banner.tsx
Labels: pr: fix & ship :ship:

#726 Form-343/Fix_Tailwindcss_bugs
  next/components/forms/icon-components/CloseIcon.tsx
  next/components/forms/icon-components/ErrorIcon.tsx
  next/components/forms/icon-components/InfoIcon.tsx
  next/components/forms/icon-components/SuccessIcon.tsx
  next/components/forms/icon-components/WarningIcon.tsx
  next/components/forms/info-components/Alert.tsx
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/components/forms/simple-components/Button.tsx
  next/components/forms/widget-components/DateTimePicker/DateField.tsx
  next/components/forms/widget-components/DateTimePicker/TimeField.tsx
  next/components/forms/widget-components/InputField/InputField.tsx
  next/components/forms/widget-components/SearchField/SearchField.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/TextAreaField/TextAreaField.tsx
  next/components/styleguide/showcases/ButtonShowCase.tsx
Labels: pr: fix & ship :ship:

#707 #637 Homepage road closures map height adjust
  next/components/ui/Iframe/Iframe.tsx
  next/components/ui/Sections/Posts/Posts.tsx
Labels: pr: fix & ship :ship:

#734 Feature/#637 change deadline
  next/components/ui/Sections/Posts/Posts.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
Labels: pr: needs review :pray:

#733 FORM-332: fit menu items width to bold content
  next/components/forms/segments/AccountNavBar/AccountNavBar.tsx
  next/pages/bratislava.css
Labels: pr: fix & ship :ship:

#737 Form 210/rjsf summary fix
  next/utils/rjsf-schema-handler.ts
Labels: pr: fix & ship :ship:

#736 Form-329/SuccessScreen_Form-Fix
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouCard.tsx
  next/components/forms/segments/AccountSections/ThankYouSection/ThankYouFormSection.tsx
Labels: pr: fix & ship :ship:

#662 Form-337/Snackbar
  next/components/styleguide/showcases/SnackbarShowCase.tsx
  next/index.d.ts
  next/package.json
  next/pages/_app.tsx
  next/pages/styleguide.tsx
  next/yarn.lock
Labels: pr: fix & ship :ship:

#716 Form 341/select changes
  next/backend/forms/test/schema.json
  next/components/forms/segments/AccountSectionHeader/MunicipalServicesSectionHeader.tsx
  next/components/forms/segments/AccountSections/MunicipalServicesSection/MunicipalServicesSection.tsx
  next/components/forms/simple-components/Tag.tsx
  next/components/forms/widget-components/SelectField/Dropdown.tsx
  next/components/forms/widget-components/SelectField/DropdownRow.tsx
  next/components/forms/widget-components/SelectField/SelectAllDropdownRow.tsx
  next/components/forms/widget-components/SelectField/SelectField.tsx
  next/components/forms/widget-components/SelectField/SelectFieldBox.tsx
  next/components/forms/widget-wrappers/SelectFieldWidgetRJSF.tsx
  next/components/styleguide/showcases/DropdownShowCase.tsx
  next/components/styleguide/showcases/SelectFieldShowCase.tsx
  next/public/locales/en/forms.json
  next/public/locales/sk/forms.json
Labels: pr: fix & ship :ship:

#739 Form-264/TaxDetails_MapTestData
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxDetails.tsx
  next/components/forms/simple-components/AccordionTableContent.tsx
  next/components/forms/simple-components/AccordionTableTaxContent.tsx
  next/components/forms/widget-components/Modals/Modal.tsx
  next/components/styleguide/showcases/AccordionShowCase.tsx
Labels: pr: fix & ship :ship:

#742 FORM-292: Fixing AccountActivator after review
  next/pages/login.tsx
  next/pages/register.tsx
Labels: pr: fix & ship :ship:

#743 FORM-331: Registration verification on /taxes-and-fees page
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesErrorCard.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesSection.tsx
  next/components/forms/segments/AccountSections/TaxesFeesSection/TaxesFeesWaitingCard.tsx
  next/public/locales/en/account.json
  next/public/locales/sk/account.json
Labels: pr: fix & ship :ship:

#744 FORM-289: Aktualne Section (/account) - fix image rounded styles
  next/components/forms/segments/AccountSections/IntroSection/AnnouncementBlock.tsx
Labels: pr: fix & ship :ship:

#738 Form 306/stepper mobile fix
  next/components/forms/steps/StepperView.tsx
  next/components/forms/steps/Summary/SummaryRow.tsx
  next/components/ui/FormRJSF/GeneratedFormRJSF.tsx
  next/utils/forms.ts
Labels: pr: fix & ship :ship:

#717 Fix UA chat
  next/components/pages/generalPage.tsx
  next/next.config.js
  next/package.json
  next/pages/_app.tsx
Labels: pr: fix & ship :ship:

#748 Remove uradna-tabula.tsx
  next/assets/images/official-board.png
  next/next.config.js
  next/pages/mesto-bratislava/transparentne-mesto/uradna-tabula.tsx
Labels: pr: fix & ship :ship:

#752 [AFTER remove-forms-account-v1] Core cleanup v2
  next/components/atoms/BlogCard.tsx
  next/components/atoms/HeadSection.tsx
  next/components/atoms/HeaderItem.tsx
  next/components/atoms/OrgStructurePersonCard.tsx
  next/components/layouts/BasePageLayout.tsx
  next/components/molecules/HeadSections.tsx
  next/components/molecules/HeaderItems.tsx
  next/components/molecules/PageHeaderSections.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/ArticlesListSection/ArticlesList.tsx
  next/components/molecules/sections/general/ArticlesListSection/ArticlesListSection.tsx
  next/components/molecules/sections/homepage/FacebookPostsHomepageSection.tsx
  next/components/molecules/sections/homepage/GooutEventsHomepageSection.tsx
  next/components/molecules/sections/homepage/InBa.tsx
  next/components/molecules/sections/homepage/RelatedBlogPosts.tsx
  next/components/molecules/sections/pageHeader/FeaturedBlogsPageHeaderSection.tsx
  next/components/molecules/sections/pageHeader/SubpageListPageHeaderSection.tsx
  next/components/pages/generalPage.tsx
  next/components/sections/WithoutStickyMenuSection.tsx
  next/components/ui/InBaCard/InBaCard.tsx
  next/components/ui/VerticalCard/VerticalCard.tsx
  next/graphql/index.ts
  next/graphql/queries/Sections.graphql
  next/pages/[...slug].tsx
  next/pages/blog/[slug].tsx
  next/pages/index.tsx
  next/pages/vyhladavanie.tsx
  next/utils/constants.tsx
Labels: pr: fix & ship :ship:

#719 Bundle analyzer
  next/next.config.js
  next/package.json
  next/yarn.lock
Labels: pr: fix & ship :ship:

#774 revert add bundle analyzer
  next/next.config.js
  next/package.json
  next/yarn.lock
Labels: pr: fix & ship :ship:

#776 Dependabot monthly without rebase
  .github/dependabot.yml
Labels: pr: fix & ship :ship:

#772 #664 new menu
  next/components/atoms/icon/Icon.tsx
  next/components/forms/simple-components/MLink.tsx
  next/components/layouts/BasePageLayout.tsx
  next/components/layouts/HomepagePageLayout.tsx
  next/components/pages/blogPostPage.tsx
  next/components/pages/generalPage.tsx
  next/components/sections/WelcomeSection.tsx
  next/components/sections/useWithoutStickyMenuSection.ts
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/BAStickyMenu/BAStickyMenu.tsx
  next/components/ui/HomepageMenu/HomePageCategoryButton.tsx
  next/components/ui/HomepageMenu/HomepageMenu.tsx
  next/components/ui/HomepageMenu/HomepageMenuIcon.tsx
  next/components/ui/HomepageMenu/HomepageMenuPanel.tsx
  next/components/ui/HomepageMenu/MenuDesktopLayout.tsx
  next/components/ui/HomepageMenu/MenuMobileLayout.tsx
  next/components/ui/HomepageMenu/useHomepageMenu.ts
  next/components/ui/NavMenu/NavMenu.tsx
  next/components/ui/NavMenu/NavMenuContent.tsx
  next/components/ui/NavMenu/NavMenuContentCell.tsx
  next/components/ui/NavMenu/NavMenuItem.tsx
  next/components/ui/NavMenu/NavMenuLink.tsx
  next/components/ui/NavMenu/NavMenuSection.tsx
  next/components/ui/NavMenu/NavMenuTrigger.tsx
  next/components/ui/NavMenu/getParsedMenus.ts
  next/components/ui/NavMenu/navMenuContext.tsx
  next/components/ui/NavMenu/navMenuTypes.ts
  next/components/ui/WelcomeCard/IconComponents/IconCity.tsx
  next/components/ui/WelcomeCard/IconComponents/IconCulture.tsx
  next/components/ui/WelcomeCard/IconComponents/IconEducation.tsx
  next/components/ui/WelcomeCard/IconComponents/IconEnvironment.tsx
  next/components/ui/WelcomeCard/IconComponents/IconSocial.tsx
  next/components/ui/WelcomeCard/IconComponents/IconTransport.tsx
  next/components/ui/WelcomeCard/WelcomeCard.stories.mdx
  next/components/ui/WelcomeCard/WelcomeCard.tsx
  next/components/ui/WelcomeCard/WelcomeCardIcon.tsx
  next/graphql/index.ts
  next/graphql/queries/General.graphql
  next/package.json
  next/pages/[...slug].tsx
  next/pages/_app.tsx
  next/pages/blog/[slug].tsx
  next/pages/index.css
  next/pages/index.tsx
  next/pages/vyhladavanie.tsx
  next/public/locales/en/common.json
  next/public/locales/sk/common.json
  next/utils/getHoverColorFromIcon.ts
  next/utils/isDefined.ts
  next/utils/page.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:

#781 #720 #777 Comparison section, Pros and Cons Section
  next/assets/images/done.svg
  next/assets/images/index.ts
  next/assets/images/info.svg
  next/assets/images/krizik.svg
  next/components/molecules/ComparisonCard.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/ComparisonSection.tsx
  next/components/molecules/sections/general/ProsAndConsSection.tsx
  next/graphql/index.ts
  next/graphql/queries/General.graphql
  next/graphql/queries/Sections.graphql
  next/tailwind.config.js
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/blocks/common-link.json
  strapi/src/components/blocks/comparison-card.json
  strapi/src/components/blocks/comparison-item.json
  strapi/src/components/blocks/pros-and-cons-card.json
  strapi/src/components/sections/comparison-section.json
  strapi/src/components/sections/pros-and-cons-section.json
Labels: pr: fix & ship :ship:

#783 #782: cleanup, simplify and crop Waves
  next/components/molecules/sections/general/WavesSection.tsx
  next/components/sections/WelcomeSection.tsx
  next/components/ui/BAStickyMenu/MenuPanel.tsx
  next/components/ui/NavMenu/NavMenuContent.tsx
  next/components/ui/NumericalListSectionUI/NumericalListSectionUI.tsx
  next/components/ui/PageHeader/PageHeader.stories.mdx
  next/components/ui/PageHeader/PageHeader.tsx
  next/components/ui/Waves/Waves.stories.mdx
  next/components/ui/Waves/Waves.tsx
  next/components/ui/Waves/waves/WaveBottomLarge.tsx
  next/components/ui/Waves/waves/WaveBottomSmall.tsx
  next/components/ui/Waves/waves/WaveTopLarge.tsx
  next/components/ui/Waves/waves/WaveTopSmall.tsx
  next/graphql/index.ts
  next/graphql/queries/Sections.graphql
  next/pages/index.tsx
  strapi/schema.graphql
  strapi/src/components/sections/waves.json
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#789 768/ navbar small cleanup
  next/components/forms/widget-components/DateTimePicker/DatePicker.tsx
  next/components/forms/widget-components/DateTimePicker/TimePicker.tsx
  next/components/layouts/BasePageLayout.tsx
  next/components/layouts/HomepagePageLayout.tsx
  next/components/layouts/PageContextProvider.tsx
  next/components/layouts/PageLayout.tsx
  next/components/molecules/Footer.tsx
  next/components/molecules/sections/general/WelcomeSection.tsx
  next/components/organisms/NavBar/MobileNavBar.tsx
  next/components/organisms/NavBar/NavBar.tsx
  next/components/organisms/NavBar/NavBarHeader/NavBarHeader.tsx
  next/components/organisms/NavBar/NavMenu/NavMenu.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuContent.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuContentCell.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuItem.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuLink.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuSection.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuTrigger.tsx
  next/components/organisms/NavBar/NavMenu/getParsedMenus.ts
  next/components/organisms/NavBar/NavMenu/navMenuContext.tsx
  next/components/organisms/NavBar/NavMenu/navMenuTypes.ts
  next/components/pages/blogPostPage.tsx
  next/components/pages/generalPage.tsx
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/NavBarHeader/NavBarHeader.tsx
  next/components/ui/Sections/Posts/Posts.tsx
  next/components/ui/WelcomeCard/WelcomeCard.tsx
  next/pages/[...slug].tsx
  next/pages/_app.tsx
  next/pages/blog/[slug].tsx
  next/pages/index.tsx
  next/pages/styleguide.tsx
  next/pages/vyhladavanie.tsx
Labels: pr: fix & ship :ship:

#791 780/mobile menu
  next/assets/images/EServices.svg
  next/assets/images/Tourist-icon.svg
  next/assets/images/ba-hamburger.svg
  next/assets/images/chevron-left-large.svg
  next/assets/images/chevron-right-large.svg
  next/assets/images/index.ts
  next/assets/images/phone-medium.svg
  next/assets/images/search-icon.svg
  next/components/atoms/icon/IconService.ts
  next/components/forms/simple-components/Button.tsx
  next/components/forms/simple-components/MLink.tsx
  next/components/layouts/PageLayout.tsx
  next/components/organisms/NavBar/MobileNavBar.tsx
  next/components/organisms/NavBar/NavBar.tsx
  next/components/organisms/NavBar/NavBarHeader/NavBarHeader.tsx
  next/components/organisms/NavBar/NavMenu/HorizontalDivider.tsx
  next/components/organisms/NavBar/NavMenu/MobileNavMenu.tsx
  next/components/organisms/NavBar/NavMenu/MobileNavMenuContent.tsx
  next/components/organisms/NavBar/NavMenu/MobileNavMenuItem.tsx
  next/components/organisms/NavBar/NavMenu/MobileNavMenuTrigger.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuContent.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuLink.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuSection.tsx
  next/components/organisms/NavBar/NavMenu/navMenuContext.tsx
  next/components/pages/blogPostPage.tsx
  next/components/pages/generalPage.tsx
  next/components/ui/BANavBar/BANavBar.stories.mdx
  next/components/ui/BANavBar/BANavBar.tsx
  next/components/ui/BAStickyMenu/BAStickyMenu.tsx
  next/components/ui/BAStickyMenu/MenuCell.tsx
  next/components/ui/BAStickyMenu/MenuPanel.tsx
  next/components/ui/BAStickyMenu/useStickyMenu.ts
  next/components/ui/HamburgerMenu/HamburgerMenu.tsx
  next/components/ui/HamburgerSubMenu/HamburgerSubMenu.tsx
  next/components/ui/HomepageMenu/HomepageMenu.tsx
  next/components/ui/Links/Links.tsx
  next/components/ui/SubpageList/SubpageList.tsx
  next/components/ui/index.ts
  next/package.json
  next/pages/[...slug].tsx
  next/pages/_app.tsx
  next/pages/blog/[slug].tsx
  next/pages/index.tsx
  next/pages/vyhladavanie.tsx
  next/tailwind.config.js
  next/utils/homepage-mockdata.ts
  next/utils/isExternalLink.ts
  next/utils/page.ts
  next/yarn.lock
  strapi/src/components/general/header.json
Labels: pr: needs review :pray:

#788 Sort org structure on the endpoint
  next/backend/services/ms-graph.ts
  next/backend/utils/organisationalStructure.ts
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordion.tsx
Labels: pr: fix & ship :ship:

#800 Fix org structure sort
  next/backend/services/ms-graph.ts
Labels: pr: fix & ship :ship:

#751 Feature/#660 banner basic
  next/components/forms/simple-components/Button.tsx
  next/components/forms/simple-components/MLink.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/BannerSection.tsx
  next/components/ui/Banner/Banner.tsx
  next/graphql/index.ts
  next/graphql/queries/Sections.graphql
  next/pages/styleguide.tsx
  next/utils/getCommonLinkProps.ts
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/banner.json
Labels: pr: fix & ship :ship:

#804 #802: change menu links to fullpath
  next/components/organisms/NavBar/NavMenu/getParsedMenus.ts
Labels: pr: fix & ship :ship:

#805 Minor improvements
  next/backend/services/ms-graph.ts
  next/components/ui/BlogSearchCard/BlogSearchCard.tsx
  next/next.config.js
  next/pages/api/latest-blogposts.tsx
  next/pages/api/ms-graph/structure.ts
  next/public/locales/sk/account.json
  next/public/locales/sk/forms.json
  next/utils/constants.tsx
  next/utils/page.ts
  strapi/schema.graphql
  strapi/src/api/general/content-types/general/schema.json
Labels: pr: fix & ship :ship:

#807 Add imageSrc
  next/components/pages/generalPage.tsx
Labels: pr: fix & ship :ship:

#811 Next pages cleanup
  next/components/layouts/PageContextProvider.tsx
  next/components/layouts/PageLayout.tsx
  next/components/molecules/Footer.tsx
  next/components/pages/blogPostPage.tsx
  next/components/pages/blogPostPageContent.tsx
  next/components/pages/generalPage.tsx
  next/components/pages/generalPageContent.tsx
  next/components/pages/searchPageContent.tsx
  next/components/ui/PageHeader/PageHeader.tsx
  next/graphql/index.ts
  next/graphql/queries/BlogPosts.graphql
  next/graphql/queries/General.graphql
  next/graphql/queries/Pages.graphql
  next/graphql/queries/Sections.graphql
  next/pages/[...slug].tsx
  next/pages/blog/[slug].tsx
  next/pages/index.tsx
  next/pages/styleguide.tsx
  next/pages/vyhladavanie.tsx
  next/utils/isDefined.ts
Labels: pr: needs review :pray:

#814 771/event card
  next/backend/services/toottoot.tsx
  next/components/styleguide/showcases/EventCardShowcase.tsx
  next/components/ui/EventCard/EventCard.tsx
  next/pages/api/toottoot-homepage-events.ts
  next/pages/styleguide.tsx
Labels: pr: fix & ship :ship:
