Repository bratislava/bratislava.sk, pull requests merged in 2023-05, with the labels that each got.

#913 remove some unused components, fix hp news
  next/components/ui/ChairSpace/ChairSpace.tsx
  next/components/ui/DateSelect/DateSelect.tsx
  next/components/ui/DateSelectShortcuts/DateSelectShortcuts.tsx
  next/components/ui/ImageCard/ImageCard.tsx
  next/components/ui/InfoCard/InfoCard.tsx
  next/components/ui/InputAccessory/InputAccessory.tsx
  next/components/ui/Sections/HomepageTabs/TabPanelLatestNews.tsx
  next/components/ui/Sections/RelatedContent/RelatedContent.tsx
  next/components/ui/Select/Select.tsx
  next/components/ui/SwitchToggle/SwitchToggle.tsx
  next/components/ui/TestCard/TestCard.tsx
  next/components/ui/TextArea/TextArea.tsx
  next/components/ui/TicketTypeCards/TicketTypeCards.tsx
  next/components/ui/TimeCardMobile/TimeCardMobile.tsx
  next/components/ui/Tooltip/Tooltip.tsx
  next/components/ui/VisibilityIntersection/VisibilityIntersectionWrapper.tsx
  next/components/ui/VisibilityIntersection/useIntersectionObserver.ts
Labels: pr: needs review :pray:

#916 #769: show related blog posts on pages
  next/components/molecules/sections/RelatedBlogPostsSection.tsx
  next/components/molecules/sections/general/OfficialBoardSection/OfficialBoardSection.tsx
  next/components/pages/generalPageContent.tsx
  next/components/providers/BAQueryClientProvider.tsx
  next/components/ui/Sections/HomepageTabs/TabPanelLatestNews.tsx
  next/graphql/fetchers/relatedBlogPosts.fetcher.ts
  next/graphql/index.ts
  next/graphql/queries/BlogPosts.graphql
  next/graphql/queries/Pages.graphql
  next/messages/en.json
  next/messages/sk.json
  next/package.json
  next/pages/[...slug].tsx
  next/utils/blogpost.ts
  next/utils/prefetchPageSections.ts
  next/yarn.lock
Labels: pr: needs review :pray:

#917 add new fields to HP
  next/graphql/index.ts
  next/graphql/queries/Homepage.graphql
  strapi/schema.graphql
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/components/blocks/homepage-highlights-item.json
  strapi/src/components/sections/homepage-highlights.json
  strapi/src/components/sections/homepage-mayor-and-council.json
  strapi/src/components/sections/homepage-tabs.json
Labels: pr: fix & ship :ship:

#918 #657: fix removing alert
  next/components/organisms/NavBar/AlertBanner.tsx
  next/graphql/index.ts
  strapi/schema.graphql
  strapi/src/api/alert/content-types/alert/schema.json
Labels: pr: fix & ship :ship:

#919 #766: hp strapi highlights
  next/assets/images/primatorReal.png
  next/components/molecules/presentation/MayorAndCouncilCard.tsx
  next/components/molecules/sections/homepage/BlogCardsPrimatorHomepageSection.tsx
  next/components/molecules/sections/homepage/MayorAndCouncilHomepageSection.tsx
  next/components/molecules/sections/homepage/NewsAndInfoHomepageSection.tsx
  next/components/molecules/sections/homepage/WelcomeHomepageSection.tsx
  next/components/pages/HomepageContent.tsx
  next/components/ui/PrimatorCard/PrimatorCard.tsx
  next/components/ui/Sections/BlogCards/HighlightsHomepageSection.tsx
  next/components/ui/Sections/HomepageTabs/HomepageTabs.tsx
  next/components/ui/Sections/HomepageTabs/TabPanelLatestNews.tsx
  next/components/ui/Sections/HomepageTabs/TabPanelOfficialBoard.tsx
  next/components/ui/Sections/HomepageTabs/TabPanelRoadClosures.tsx
  next/components/ui/Sections/PrimatorCouncil/PrimatorCouncil.tsx
  next/components/ui/images/BACoatOfArms.svg
  next/components/ui/images/PrenajomImage.png
  next/components/ui/images/Primator.png
  next/components/ui/images/primatorReal.png
  next/graphql/index.ts
  next/graphql/queries/Homepage.graphql
  next/messages/en.json
  next/messages/sk.json
  strapi/schema.graphql
  strapi/src/components/blocks/homepage-highlights-item.json
  strapi/src/components/sections/homepage-highlights.json
Labels: pr: fix & ship :ship:

#921 fix: change cert issuer to dns01 for all redirects
  next/kubernetes/base/platbadane.ingress.yml
  next/kubernetes/base/ukrajina.ingress.yml
Labels: pr: infrastructure

#920 Update Next
  next/package.json
  next/yarn.lock
Labels: pr: needs review :pray:

#923 #922: use new Cards for Featured BlogPosts
  next/components/molecules/PageHeaderSections.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/presentation/BlogPostCard.tsx
  next/components/molecules/presentation/BlogPostHorizontalCard.tsx
  next/components/molecules/presentation/BlogPostImageCard.tsx
  next/components/molecules/presentation/HomepageHorizontalCard.tsx
  next/components/molecules/sections/general/ArticlesListSection/ArticlesList.tsx
  next/components/molecules/sections/pageHeader/FeaturedBlogPostsSection.tsx
  next/components/molecules/sections/pageHeader/FeaturedBlogsPageHeaderSection.tsx
  next/components/pages/generalPageContent.tsx
  next/components/ui/FeaturedBlogPosts/FeaturedBlogPosts.tsx
  next/components/ui/FeaturedBlogs/FeaturedBlogs.tsx
  next/components/ui/NewsCard/NewsCard.tsx
  next/components/ui/Sections/News/News.tsx
  next/graphql/index.ts
  next/graphql/queries/Pages.graphql
  next/graphql/queries/Sections.graphql
  next/pages/[...slug].tsx
  next/tailwind.config.js
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
Labels: pr: fix & ship :ship:

#925 Update deploy pipeline and Strapi Dockerfile
  .github/workflows/deploy.yml
  strapi/Dockerfile
Labels: pr: infrastructure

#932 Fix gen
  next/codegen.yml
Labels: pr: needs review :pray:

#936 use standardized Next Dockerfile and .dockerignore files
  next/.dockerignore
  next/Dockerfile
  strapi/.dockerignore
Labels: pr: infrastructure

#937 add output:standalone to next config
  next/next.config.js
Labels: pr: infrastructure

#938 allows iframes to open links in new tab
  next/components/ui/Iframe/Iframe.tsx
Labels: pr: fix & ship :ship:

#940 #771: add events homepage section into Strapi
  next/backend/fetchers/homepageContextFetcher.ts
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Homepage.graphql
  next/backend/services/tootoot.tsx
  next/components/pages/HomepageContent.tsx
  next/components/ui/Iframe/Iframe.tsx
  next/next.config.js
  next/pages/api/tootoot-homepage-events.ts
  strapi/schema.graphql
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/components/sections/homepage-events.json
Labels: pr: fix & ship :ship:

#942 Fix index
  next/components/molecules/sections/general/ArticlesListSection/ArticlesList.tsx
Labels: pr: needs review :pray:

#943 Fix and refactor prefetching related blogs
  next/backend/graphql/fetchers/relatedBlogPosts.fetcher.ts
  next/components/molecules/sections/general/RelatedBlogPostsSection.tsx
  next/components/pages/generalPageContent.tsx
  next/utils/prefetchPageSections.ts
Labels: pr: fix & ship :ship:

#945 #944: refactor section container and screen sizes and spacing
  next/components/molecules/presentation/BlogPostCard.tsx
  next/components/molecules/sections/homepage/GooutEventsHomepageSection.tsx
  next/components/molecules/sections/homepage/HighlightsHomepageSection.tsx
  next/components/molecules/sections/homepage/HomepageTabs/HomepageTabs.tsx
  next/components/molecules/sections/homepage/HomepageTabs/TabPanelLatestNews.tsx
  next/components/molecules/sections/homepage/InbaHomepageSection.tsx
  next/components/molecules/sections/homepage/NewsAndInfoHomepageSection.tsx
  next/components/molecules/sections/homepage/TopServicesHomepageSection.tsx
  next/components/molecules/sections/homepage/WelcomeHomepageSection.tsx
  next/components/organisms/NavBar/NavMenu/NavMenu.tsx
  next/components/organisms/NavBar/NavMenu/NavMenuContent.tsx
  next/components/styleguide/StyleGuideWrapper.tsx
  next/components/ui/PageHeader/PageHeader.tsx
  next/components/ui/SectionContainer/SectionContainer.tsx
  next/components/ui/TopServices/TopServices.tsx
  next/components/ui/Waves/Waves.tsx
  next/styles/globals.css
  next/tailwind.config.screens.js
Labels: pr: fix & ship :ship:

#946 #771: show events from tootoot
  next/backend/services/tootoot.tsx
  next/components/atoms/FormatEventDateRange.tsx
  next/components/molecules/presentation/EventCard.tsx
  next/components/molecules/sections/homepage/EventsHomepageSection.tsx
  next/components/molecules/sections/homepage/GooutEventsHomepageSection.tsx
  next/components/pages/HomepageContent.tsx
  next/components/styleguide/showcases/EventCardShowcase.tsx
  next/components/ui/Carousel/Carousel.tsx
  next/components/ui/TopServicesItem/TopServicesItem.tsx
  next/messages/en.json
  next/messages/sk.json
  next/next.config.js
  next/pages/api/goout-events.ts
  next/utils/consts.ts
  next/utils/goout.ts
  next/utils/parseGooutScheduleResponse.ts
Labels: pr: fix & ship :ship:

#949 fix: change HOSTNAME to BRATISKA_HOSTNAME for redirects
  next/kubernetes/base/ukrajina.ingress.yml
Labels: pr: infrastructure

#950 #871: order of deputy roles in organizational structure
  next/backend/services/ms-graph.ts
Labels: pr: needs review :pray:

#951 #829: remove ListItems section
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Sections.graphql
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/ListItemsSection.tsx
  next/components/ui/ListItem/ListItem.tsx
  next/components/ui/ListItems/ListItems.tsx
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/blocks/list-item.json
  strapi/src/components/sections/list-items.json
Labels: pr: needs review :pray:

#947 #934: implement Blog Posts list by tags, prepared for future filtering
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Sections.graphql
  next/backend/meili/fetchers/blogPostsFetcherReactQuery.ts
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/ArticlesListSection/BlogPostsByTags.tsx
  next/utils/useRoutePreservedState.ts
  strapi/config/plugins.meilisearch.config.ts
  strapi/schema.graphql
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/blog-posts-list.json
Labels: pr: needs review :pray:

#952 #637: set Road Closures Map to be displayed after 1st June in HP tabs section
  next/components/molecules/sections/homepage/HomepageTabs/TabPanelRoadClosures.tsx
Labels: pr: fix & ship :ship:

#957 Cleanup more old components
  next/backend/fetchers/homepageContextFetcher.ts
  next/backend/graphql/fetchers/relatedBlogPosts.fetcher.ts
  next/backend/graphql/gql.ts
  next/backend/meili/fetchers/blogPostsFetcher.ts
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordionCard.tsx
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordionCards.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/ArticlesListSection/ArticlesList.tsx
  next/components/molecules/sections/general/DocumentListSection/DocumentListModalBody.tsx
  next/components/molecules/sections/general/FeaturedBlogPostsSection.tsx
  next/components/molecules/sections/general/GallerySection.tsx
  next/components/molecules/sections/homepage/InbaHomepageSection.tsx
  next/components/organisms/Carousel/Carousel.tsx
  next/components/ui/AccordionCards/AccordionCards.tsx
  next/components/ui/AdvancedAccordion/AdvancedAccordion.tsx
  next/components/ui/AdvancedAccordionDepartment/AdvancedAccordionDepartment.tsx
  next/components/ui/AdvancedAccordionItem/AdvancedAccordionItem.tsx
  next/components/ui/AdvancedAccordionSubSubitem/AdvancedAccordionSubSubitem.tsx
  next/components/ui/AdvancedAccordionSubitem/AdvancedAccordionSubitem.tsx
  next/components/ui/ArticlesFilter/ArticlesFilter.tsx
  next/components/ui/BlogSearchCard/BlogSearchCard.tsx
  next/components/ui/BlogSearchCards/BlogSearchCards.tsx
  next/components/ui/FileList/FileList.tsx
  next/components/ui/HorizontalScrollWrapper/HorizontalScrollWrapper.tsx
  next/components/ui/InBaCard/InBaCard.tsx
  next/components/ui/PageCard/PageCard.tsx
  next/components/ui/PageCards/PageCards.tsx
  next/components/ui/Videos/Videos.tsx
  next/pages/[...slug].tsx
  next/pages/api/feed.ts
  next/pages/blog/[slug].tsx
  next/pages/index.tsx
  next/pages/vyhladavanie.tsx
Labels: pr: fix & ship :ship:

#958 #956: remove ua chatbot
  next/assets/images/message.svg
  next/components/molecules/chat.tsx
  next/components/pages/generalPageContent.tsx
  next/package.json
  next/styles/globals.css
  next/yarn.lock
Labels: pr: fix & ship :ship:

#959 #771: fix date local
  next/components/organisms/Carousel/Carousel.tsx
  next/components/providers/BAI18nProvider.tsx
  next/pages/_app.tsx
Labels: pr: fix & ship :ship:

#960 fix url in Next Dockerfile
  next/Dockerfile
Labels: pr: infrastructure
