Repository bratislava/bratislava.sk, pull requests merged in 2023-10, with the labels that each got.

#1084 Bump react-aria-components
  next/components/forms/simple-components/Toggle.tsx
  next/components/molecules/sections/homepage/HomepageTabs/HomepageTabs.tsx
  next/components/styleguide/showcases/BlogPostCardShowcase.tsx
  next/components/styleguide/showcases/CategoryCardShowcase.tsx
  next/components/styleguide/showcases/HomepageHorizontalCardShowcase.tsx
  next/components/ui/Bookmark/Bookmark.tsx
  next/components/ui/Contacts/Contacts.tsx
  next/components/ui/ModalDialog/ModalDialog.tsx
  next/package.json
  next/pages/_app.tsx
  next/styles/colors.css
  next/tailwind.config.js
  next/yarn.lock
Labels: pr: fix & ship :ship:

#988 chore: switch app certificate to issue through cloudflare DNS
  next/kubernetes/base/platbadane.ingress.yml
  next/kubernetes/base/ukrajina.ingress.yml
Labels: pr: fix & ship :ship:, pr: infrastructure

#1087 improve Modal and Dialog scrollable content
  next/components/forms/simple-components/Button.tsx
  next/components/molecules/presentation/FileCard.tsx
  next/components/molecules/presentation/FileRowCard.tsx
  next/components/molecules/sections/general/DocumentListSection/RegulationModalBody.tsx
  next/components/molecules/sections/general/DocumentListSection/RegulationsResults.tsx
  next/components/ui/ModalDialog/Dialog.tsx
  next/components/ui/ModalDialog/Modal.tsx
  next/components/ui/ModalDialog/ModalDialog.tsx
  next/components/ui/OfficialBoardCard/OfficialBoardCard.tsx
  next/components/ui/OfficialBoardCard/OfficialBoardCardModalContent.tsx
  next/components/ui/RegulationListItem/RegulationListItem.tsx
Labels: pr: fix & ship :ship:

#1089 Bump react aria libraries and fix dependent component
  next/components/ui/ModalDialog/Dialog.tsx
  next/package.json
  next/yarn.lock
Labels: pr: needs review :pray:

#1090 fix: change values of GINIS secret
  next/kubernetes/base/secrets/ginis.secret.all.yml
Labels: pr: fix & ship :ship:, pr: infrastructure

#1096 Fix hydration error with img in Markup component
  next/components/atoms/Markdown.tsx
  next/package.json
  next/yarn.lock
Labels: pr: fix & ship :ship:

#1094 Fix gradient on Blog post cards
  next/components/molecules/presentation/BlogPostImageCard.tsx
Labels: pr: fix & ship :ship:

#1095 1083/tag group
  next/backend/graphql/index.ts
  next/backend/graphql/queries/InbaArticles.graphql
  next/components/forms/simple-components/Chip.tsx
  next/components/molecules/sections/general/ArticlesListSection/InbaArticlesByTags.tsx
  next/components/ui/InbaArticlesFilter/InbaArticlesFilter.tsx
  next/messages/en.json
  next/messages/sk.json
Labels: pr: fix & ship :ship:

#1101 Add new component BlogPostsByTags in Strapi
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Sections.graphql
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/ArticlesListSection/BlogPostsByTags.tsx
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/blog-posts-by-tags.json
Labels: pr: fix & ship :ship:
