Repository bratislava/bratislava.sk, pull requests merged in 2024-01, with the labels that each got.

#1153 Upgrade graphql libraries
  next/backend/graphql/index.ts
  next/package.json
  next/yarn.lock
Labels: pr: fix & ship :ship:, issue: graphql

#1154 Remove ContactSection and Contact from strapi and next
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Sections.graphql
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/ContactSection.tsx
  next/components/ui/Contact/Contact.tsx
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/contact.json
Labels: pr: fix & ship :ship:

#1150 1093/search redesign
  next/assets/icons-top-services/elektronicke-sluzby.svg
  next/assets/icons-top-services/kampane-a-projekty.svg
  next/assets/icons-top-services/kontakty-a-uradne-hodiny.svg
  next/assets/icons-top-services/miestne-dane-a-poplatky.svg
  next/assets/icons-top-services/nahlasenie-podnetov.svg
  next/assets/icons-top-services/organizacna-struktura.svg
  next/assets/icons-top-services/parky-a-zahrady.svg
  next/assets/icons-top-services/pracovne-prilezitosti.svg
  next/assets/icons-top-services/prenajom-priestorov.svg
  next/assets/icons-top-services/turistom-v-hlavnom-meste.svg
  next/assets/images/dokumenty.svg
  next/backend/meili/fetchers/blogPostsFetcher.ts
  next/backend/meili/fetchers/pagesFetcher.ts
  next/components/atoms/icon/IconService.ts
  next/components/forms/simple-components/Chip.tsx
  next/components/molecules/SearchPageNew/AdvancedSearchNew.tsx
  next/components/molecules/SearchPageNew/GeneralSearchResults.tsx
  next/components/molecules/SearchPageNew/SearchCardComposed.tsx
  next/components/molecules/SearchPageNew/SearchResultsHeader.tsx
  next/components/molecules/SearchPageNew/useQueryBySearchOption.ts
  next/components/pages/searchPageContent.tsx
  next/components/pages/searchPageContentNew.tsx
  next/messages/en.json
  next/messages/sk.json
  next/pages/vyhladavanie.tsx
  next/tailwind.config.js
  next/utils/colors.tsx
  next/utils/pageIcons.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1149 Add check for blogpostcard if in carousel or grid
  next/components/molecules/presentation/EventCard.tsx
  next/components/molecules/sections/general/ArticlesListSection/BlogPostsByCategory.tsx
  next/components/molecules/sections/homepage/EventsHomepageSection.tsx
  next/components/molecules/sections/homepage/HighlightsHomepageSection.tsx
  next/components/organisms/Carousel/Carousel.tsx
  next/components/styleguide/showcases/EventCardShowcase.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1162 remove legacy accordion bigger gap
  next/components/molecules/sections/general/AccordionSection.tsx
  next/components/ui/AccordionV2/AccordionV2.tsx
Labels: pr: fix & ship :ship:

#1163 1159/search results minor updates
  next/assets/icons-search-results/dokumenty.svg
  next/assets/icons-search-results/index.ts
  next/assets/icons-search-results/kontakty-a-uradne-hodiny.svg
  next/components/atoms/icon/IconService.ts
  next/components/molecules/SearchPageNew/GeneralSearchResults.tsx
  next/components/molecules/SearchPageNew/SearchCardComposed.tsx
  next/components/molecules/SearchPageNew/useQueryBySearchOption.ts
Labels: pr: fix & ship :ship:, issue: react
