Repository bratislava/bratislava.sk, pull requests merged in 2024-02, with the labels that each got.

#1166 1158 0/add regulation collection
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Regulation.graphql
  strapi/schema.graphql
  strapi/src/api/regulation/content-types/regulation/schema.json
  strapi/src/api/regulation/controllers/regulation.ts
  strapi/src/api/regulation/routes/regulation.ts
  strapi/src/api/regulation/services/regulation.ts
Labels: pr: fix & ship :ship:, issue: strapi

#1168 Disable draft&publish for Regulations temporarily and fix textTitle f…
  next/backend/graphql/queries/Regulations.graphql
  strapi/schema.graphql
  strapi/src/api/regulation/content-types/regulation/schema.json
Labels: pr: fix & ship :ship:, issue: strapi

#1170 1158 1/replace vzn with regulation next components
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Regulations.graphql
  next/components/molecules/Regulations/RegulationCard.tsx
  next/components/molecules/Regulations/RegulationDetailMessage.tsx
  next/components/pages/RegulationPageContent.tsx
  next/messages/sk.json
  next/pages/vzn/[slug].tsx
  strapi/schema.graphql
  strapi/src/api/regulation/content-types/regulation/schema.json
Labels: pr: fix & ship :ship:, pr: needs review :pray:, issue: strapi, issue: react

#1177 fix: revert back to local hosted GitHub runners
  .github/workflows/deploy.yml
Labels: pr: fix & ship :ship:, pr: infrastructure

#1178 fix: move build pipeline to local GH action runner
  .github/workflows/build.yml
Labels: pr: fix & ship :ship:, pr: infrastructure

#1173 Change inba articles url
  next/components/molecules/Regulations/RegulationCard.tsx
  next/components/molecules/SearchPageNew/useQueryBySearchOption.ts
  next/components/molecules/sections/general/ArticlesListSection/InbaArticlesList.tsx
  next/components/pages/InbaArticlePageContent.tsx
  next/components/styleguide/showcases/AccordionShowcase.tsx
  next/components/ui/InbaFeaturedArticles/InbaFeaturedArticles.tsx
  next/pages/blog/[slug].tsx
  next/pages/inba/archiv/[slug].tsx
  next/pages/inba/clanky/[slug].tsx
  next/pages/vzn/[slug].tsx
Labels: pr: fix & ship :ship:

#1176 Fix/eslint setup
  next/.eslintrc.js
  next/components/molecules/sections/general/OfficialBoardSection/OfficialBoardSection.tsx
  next/components/molecules/sections/general/TextWithImageSection.tsx
  next/components/molecules/sections/homepage/HomepageTabs/TabPanelOfficialBoard.tsx
  next/components/styleguide/showcases/SelectFieldShowCase.tsx
  next/components/ui/Divider/Divider.tsx
  next/components/ui/Footer/FooterShared.tsx
  next/components/ui/InbaArticlesFilter/InbaArticlesFilter.tsx
  next/components/ui/OfficialBoardCard/OfficialBoardCard.tsx
  next/components/ui/OfficialBoardCards/OfficialBoardCards.tsx
  next/components/ui/Pagination/Pagination.tsx
  next/components/ui/TextWithImage/TextWithImage.tsx
  next/pages/404.tsx
  next/pages/[...slug].tsx
  next/pages/blog/[slug].tsx
  next/pages/styleguide.tsx
  next/pages/vyhladavanie.tsx
  next/utils/colors.tsx
  next/utils/homepageContext.tsx
  next/utils/page.ts
Labels: pr: fix & ship :ship:

#1180 chore: added old*.bratislava.sk aliases/redirects
  next/kubernetes/base/kustomization.yml
  next/kubernetes/base/old_aliases.ingress.yml
Labels: pr: fix & ship :ship:, pr: infrastructure

#1190 Fix visuals
  next/backend/graphql/index.ts
  next/components/molecules/SearchPageNew/useQueryBySearchOption.ts
  next/components/molecules/sections/general/RegulationsListSection/RegulationsListSection.tsx
  next/components/pages/RegulationPageContent.tsx
  next/messages/sk.json
Labels: pr: fix & ship :ship:

#1191 1158 3/replace vzn with regulations file list replacement
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Sections.graphql
  next/components/molecules/Regulations/RegulationCard.tsx
  next/components/molecules/Regulations/Regulations.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/RegulationsSection.tsx
  next/components/ui/FileList/FileList.tsx
  next/messages/en.json
  next/messages/sk.json
  strapi/schema.graphql
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/regulations.json
Labels: pr: fix & ship :ship:

#1192 Hide regulations from search
  next/components/pages/searchPageContentNew.tsx
Labels: pr: fix & ship :ship:

#1193 1158 4/replace vzn with regulations regulation page fixes
  next/components/molecules/HomePageSearch.tsx
  next/components/molecules/Regulations/RegulationCard.tsx
  next/components/molecules/Regulations/Regulations.tsx
  next/components/pages/RegulationPageContent.tsx
  next/messages/en.json
  next/messages/sk.json
Labels: pr: fix & ship :ship:
