Repository bratislava/bratislava.sk, pull requests merged in 2024-03, with the labels that each got.

#1195 1179/clean files related to new search
  next/components/molecules/SearchPage/BlogPostsResults.tsx
  next/components/molecules/SearchPage/PagesResults.tsx
  next/components/molecules/SearchPage/UsersResults.tsx
  next/components/molecules/Sections.tsx
  next/components/molecules/presentation/RegulationCard/RegulationCard.tsx
  next/components/molecules/presentation/RegulationCard/RegulationDetailMessage.tsx
  next/components/molecules/sections/general/DocumentListSection/RegulationsResults.tsx
  next/components/molecules/sections/general/Regulations.tsx
  next/components/molecules/sections/general/RegulationsListSection.tsx
  next/components/molecules/sections/general/RegulationsSection.tsx
  next/components/organisms/SearchPage/LoadingOverlay.tsx
  next/components/organisms/SearchPage/SearchBar.tsx
  next/components/organisms/SearchPage/SearchResultCard.tsx
  next/components/organisms/SearchPage/SearchResults.tsx
  next/components/organisms/SearchPage/SearchResultsHeader.tsx
  next/components/organisms/SearchPage/useQueryBySearchOption.ts
  next/components/pages/RegulationPageContent.tsx
  next/components/pages/SearchPageContent.tsx
  next/components/pages/searchPageContent.tsx
  next/components/ui/SearchBarDeprecated/SearchBarDeprecated.tsx
  next/pages/api/ms-graph/search-in-structure.ts
  next/pages/vyhladavanie.tsx
Labels: pr: fix & ship :ship:

#1197 Enable TS strict and remove unused typescript-strict-plugin
  next/tsconfig.json
Labels: pr: fix & ship :ship:

#1182 Cypress init
  tests/.eslintrc.js
  tests/.gitignore
  tests/.prettierrc.js
  tests/README.md
  tests/cypress.config.ts
  tests/cypress.sh
  tests/cypress/e2e/index.cy.ts
  tests/cypress/fixtures/example.json
  tests/cypress/support/commands/global.ts
  tests/cypress/support/e2e.ts
  tests/cypress/support/triggers/before.ts
  tests/package.json
  tests/tsconfig.json
  tests/yarn.lock
Labels: pr: fix & ship :ship:

#1206 upgrade react-query to v5
  next/components/molecules/OrganizationalStructure/OrganizationalStructure.tsx
  next/components/molecules/sections/general/ArticlesListSection/BlogPostsByCategory.tsx
  next/components/molecules/sections/general/ArticlesListSection/BlogPostsByTags.tsx
  next/components/molecules/sections/general/ArticlesListSection/BlogPostsList.tsx
  next/components/molecules/sections/general/ArticlesListSection/InbaArticlesList.tsx
  next/components/molecules/sections/general/InbaReleasesSection.tsx
  next/components/organisms/SearchPage/useQueryBySearchOption.ts
  next/components/ui/OfficialBoardCard/OfficialBoardCardModalContent.tsx
  next/package.json
  next/pages/[...slug].tsx
  next/utils/prefetchPageSections.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:

#1207 Feat/1204 search spinner
  next/components/forms/simple-components/Spinner.tsx
  next/components/molecules/ShareButtons.tsx
  next/components/molecules/sections/general/DocumentListSection/RegulationsResults.tsx
  next/components/molecules/sections/general/OfficialBoardSection/OfficialBoardSection.tsx
  next/components/molecules/sections/general/RegulationsListSection.tsx
  next/components/molecules/sections/homepage/HomepageTabs/TabPanelOfficialBoard.tsx
  next/components/organisms/SearchPage/SearchResults.tsx
  next/components/organisms/SearchSection/GlobalSearchSectionContent.tsx
  next/components/organisms/SearchSection/LoadingOverlay.tsx
  next/components/organisms/SearchSection/SearchBar.tsx
  next/components/organisms/SearchSection/SearchResultCard.tsx
  next/components/organisms/SearchSection/SearchResults.tsx
  next/components/organisms/SearchSection/SearchResultsHeader.tsx
  next/components/organisms/SearchSection/useQueryBySearchOption.ts
  next/components/pages/BlogPostPageContentTmp.tsx
  next/components/pages/GeneralPageContentTmp.tsx
  next/pages/[...slug].tsx
  next/pages/blog/[slug].tsx
  next/pages/vyhladavanie.tsx
Labels: pr: fix & ship :ship:

#1211 unify accordion sizes to only one
  next/components/molecules/sections/general/AccordionSection.tsx
  next/components/styleguide/showcases/AccordionShowcase.tsx
  next/components/ui/AccordionV2/AccordionV2.tsx
Labels: pr: fix & ship :ship:

#1213 #1185 cypress official board tests
  next/components/molecules/sections/homepage/HomepageTabs/HomepageTabs.tsx
  next/components/molecules/sections/homepage/HomepageTabs/TabPanelOfficialBoard.tsx
  next/components/organisms/SearchSection/SearchBar.tsx
  next/components/organisms/SearchSection/SearchResultCard.tsx
  next/components/organisms/SearchSection/SearchResults.tsx
  next/components/ui/Pagination/Pagination.tsx
  tests/cypress/e2e/index.cy.ts
  tests/cypress/e2e/officialBoard.cy.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1212 #1186 #1187 cypress search tests
  next/components/molecules/HomePageSearchField.tsx
  next/components/molecules/HomePageSearchResults.tsx
  next/components/organisms/NavBar/MobileNavBar.tsx
  next/components/organisms/NavBar/NavBarHeader/NavBarHeader.tsx
  next/components/organisms/SearchSection/GlobalSearchSectionContent.tsx
  next/components/organisms/SearchSection/SearchResults.tsx
  next/components/organisms/SearchSection/SearchResultsHeader.tsx
  next/components/ui/BasicSearch/BasicSearch.tsx
  tests/cypress/e2e/homepageSearch.cy.ts
  tests/cypress/e2e/searchPage.cy.ts
Labels: pr: fix & ship :ship:

#1214 Tax administrators
  strapi/schema.graphql
  strapi/src/api/tax-administrators-list/content-types/tax-administrators-list/schema.json
  strapi/src/api/tax-administrators-list/controllers/tax-administrators-list.ts
  strapi/src/api/tax-administrators-list/routes/tax-administrators-list.ts
  strapi/src/api/tax-administrators-list/services/tax-administrators-list.ts
  strapi/src/components/tax-administrators/tax-administrator.json
Labels: pr: fix & ship :ship:

#1217 use local query client
  next/components/providers/BAQueryClientProvider.tsx
Labels: pr: fix & ship :ship:

#1224 minor update in strapi setting according to template repo
  strapi/config/env/production/plugins.ts
  strapi/config/server.ts
Labels: pr: fix & ship :ship:

#1227 1219/regulations many small fixes after meeting
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Regulations.graphql
  next/components/molecules/presentation/RegulationCard/RegulationCard.tsx
  next/components/molecules/sections/general/Regulations.tsx
  next/components/pages/RegulationPageContent.tsx
  next/messages/en.json
  next/messages/sk.json
  strapi/schema.graphql
  strapi/src/api/regulation/content-types/regulation/schema.json
  strapi/src/components/sections/regulations-list.json
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1230 move strapi logger middleware to first place to meet migration guides
  strapi/config/middlewares.ts
Labels: pr: fix & ship :ship:

#1231 add strapi content default local env
  strapi/.env.example
  strapi/kubernetes/base/.env
  strapi/src/admin/app.example.tsx
  strapi/src/admin/app.tsx
  strapi/src/admin/webpack.config.example.ts
Labels: pr: fix & ship :ship:

#1233 minor visual fixes in search result cards
  next/components/molecules/sections/homepage/HomepageTabs/TabPanelOfficialBoard.tsx
  next/components/organisms/SearchSection/SearchResultCard.tsx
  next/components/organisms/SearchSection/useQueryBySearchOption.ts
Labels: pr: fix & ship :ship:

#1216 #1215 add filter by publication state to official board
  next/backend/ginis/fetchers/officialBoardListFetcher.ts
  next/backend/ginis/server/getOfficialBoardParsedList.ts
  next/backend/ginis/types.ts
  next/components/molecules/sections/general/OfficialBoardSection/OfficialBoardAdditionalFilters.tsx
  next/components/organisms/SearchSection/GlobalSearchSectionContent.tsx
  next/ginis-sdk/api/json/ude/seznam-dokumentu.ts
  next/messages/en.json
  next/messages/sk.json
  next/pages/api/ginis/official-board-list.ts
Labels: pr: fix & ship :ship:

#1235 1234/add aditional functionality to regulations
  next/backend/meili/fetchers/homepageSearchFetcher.ts
  next/backend/meili/types.ts
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/RegulationsListSection.tsx
  next/components/organisms/SearchSection/GlobalSearchSectionContent.tsx
Labels: pr: fix & ship :ship:

#1236 Fix tax administrator regex so it accepts more than two string instances
  strapi/src/components/tax-administrators/tax-administrator.json
Labels: pr: fix & ship :ship:

#1239 add Testimonials section to strapi
  next/backend/graphql/index.ts
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/blocks/testimonial-item.json
  strapi/src/components/sections/testimonials.json
Labels: pr: needs review :pray:

#1240 add Testimonials FE components
  next/backend/graphql/index.ts
  next/backend/graphql/queries/Sections.graphql
  next/components/molecules/Sections.tsx
  next/components/molecules/sections/general/TestimonialsSection.tsx
Labels: pr: fix & ship :ship:

#1244 #1242: fix shrinking link icons
  next/components/forms/simple-components/Button.tsx
  next/components/ui/Brand/Brand.tsx
  next/components/ui/Breadcrumbs/DesktopBreadcrumbs.tsx
  next/components/ui/Links/Links.tsx
Labels: pr: fix & ship :ship:
