Repository bratislava/bratislava.sk, pull requests merged in 2024-05, with the labels that each got.

#1252 #1251 Add smoke tests
  tests/cypress/e2e/smokeTests/pageStatusVerification.cy.ts
  tests/cypress/fixtures/URLsForSmokeTests.json
Labels: pr: fix & ship :ship:

#1254 #1249 Add VZN to search tests
  tests/cypress/e2e/homepageSearch.cy.ts
  tests/cypress/e2e/searchPage.cy.ts
Labels: pr: fix & ship :ship:

#1260 #1259 Add redirects for new slugs of contact pages
  next/next.config.js
Labels: pr: fix & ship :ship:

#1262 #1261 Cleanup duplicate redirects
  next/next.config.js
  next/pages/api/robots.ts
Labels: pr: needs review :pray:

#1258 1250 cypress organizational structure
  next/components/molecules/OrganizationalStructure/OrganizationalStructureAccordionCard.tsx
  tests/cypress/e2e/organizationalStructure.cy.ts
Labels: pr: fix & ship :ship:

#1266 Add new test for 404 page
  next/pages/404.tsx
  tests/cypress/e2e/404Page.cy.ts
Labels: pr: fix & ship :ship:

#1272 Fix text size in Markdown small variant
  next/components/atoms/Markdown.tsx
Labels: pr: fix & ship :ship:

#1270 Add english translation test
  next/components/atoms/Markdown.tsx
  next/components/organisms/NavBar/MobileNavBar.tsx
  next/components/organisms/NavBar/NavBarHeader/NavBarHeader.tsx
  tests/cypress/e2e/englishTranslation.cy.ts
Labels: pr: fix & ship :ship:

#1269 Add account button test
  next/components/organisms/NavBar/MobileNavBar.tsx
  next/components/organisms/NavBar/NavBarHeader/NavBarHeader.tsx
  next/components/organisms/NavBar/NavMenu/MobileNavMenu.tsx
  tests/cypress/e2e/accountButton.cy.ts
Labels: pr: fix & ship :ship:

#1257 Added k8 Ingress alias for behdevin.bratislava.sk
  next/kubernetes/envs/Prod/behdevin.ingress.yml
  next/kubernetes/envs/Prod/kustomization.yml
Labels: pr: fix & ship :ship:, pr: infrastructure

#1282 Fix: english translation
  tests/cypress/e2e/englishTranslation.cy.ts
Labels: pr: fix & ship :ship:

#1285 Reduce the number of displayed news on homepage to prevent too much h…
  next/components/sections/homepage-sections/HomepageTabs/TabPanelLatestNews.tsx
Labels: pr: fix & ship :ship:
