Repository bratislava/bratislava.sk, pull requests merged in 2025-08, with the labels that each got.

#1733 #1569 Redesign inba release detail page header
  next/src/components/cards/InbaReleaseCard.tsx
  next/src/components/common/Button/Button.tsx
  next/src/components/common/PageHeader/PageHeader.tsx
  next/src/components/page-contents/InbaReleasePageContent.tsx
  next/src/styles/globals.css
Labels: pr: fix & ship :ship:

#1741 #1739 Refactor page headers to allow more header types
  next/src/components/common/PageHeader/PageHeader.tsx
  next/src/components/layouts/PageHeaderSections.tsx
  next/src/components/page-contents/GeneralPageContent.tsx
  next/src/components/sections/headers/SubpageListPageHeaderSection_Deprecated.tsx
  strapi/src/api/page/content-types/page/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1746 #1740 Always show image placeholder in SearchResultCard
  next/src/components/sections/SearchSection/SearchResultCard.tsx
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1751 #1750 Table of contents small fixes
  next/src/components/common/TableOfContents/TableOfContents.tsx
  next/src/components/layouts/Sections.tsx
  next/src/components/page-contents/GeneralPageContent.tsx
Labels: pr: fix & ship :ship:

#1749 #1702 Events section
  next/public/locales/en/translation.json
  next/public/locales/sk/translation.json
  next/src/components/cards/EventCard.tsx
  next/src/components/cards/TootootEventCard.tsx
  next/src/components/layouts/Sections.tsx
  next/src/components/sections/EventsSection.tsx
  next/src/components/sections/TootootEventsSection.tsx
  next/src/components/styleguide/showcases/TootootEventCardShowcase.tsx
  next/src/pages/styleguide.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Pages.graphql
  next/src/services/graphql/queries/Sections.graphql
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.events.json
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/events.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1757 #1644 Fix 404 test after changes
  tests/cypress/e2e/404Page.cy.ts
Labels: pr: fix & ship :ship:

#1761 Delete 404 cypress test
  tests/cypress/e2e/404Page.cy.ts
Labels: pr: needs review :pray:

#1770 #1640 Use latest inba relese images on homepage
  next/src/components/cards/InBaCard.tsx
  next/src/components/common/InbaArticlesFilter/InbaArticlesFilter.tsx
  next/src/components/sections/SubnavigationSection.tsx
  next/src/components/sections/homepage-sections/InbaHomepageSection.tsx
  next/src/services/fetchers/homepageContextFetcher.ts
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Homepage.graphql
  next/src/services/graphql/queries/InbaReleases.graphql
  strapi/schema.graphql
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/components/blocks/in-ba.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1769 Setup running local scripts with ts-node
  next/README.md
  next/package-lock.json
  next/package.json
  next/scripts/dev/getAllUsedFilesInMediaLibrary.ts
  next/scripts/dev/migrateFilesToDocuments.ts
  next/scripts/dev/migrateSubnavigation.ts
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Files.graphql
  next/src/services/graphql/queries/Pages.graphql
  next/tsconfig.json
Labels: pr: fix & ship :ship:

#1778 #1772 Enable hiding SectionHeader heading from ToC, hide in RelatedArticlesSection
  next/src/components/layouts/SectionHeader.tsx
  next/src/components/sections/RelatedArticlesSection.tsx
Labels: pr: fix & ship :ship:

#1780 #1776 Merge regulations list section and regulations section to one
  next/src/components/sections/RegulationsSection.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Sections.graphql
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.regulations.json
  strapi/schema.graphql
  strapi/src/components/sections/regulations.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1783 Fix Spinner styling, Align title to left in Accordion section, use Markdown renderer for Columns item
  next/src/components/common/ColumnsSectionItem/ColumnsSectionItem.tsx
  next/src/components/common/Spinner/Spinner.tsx
  next/src/components/sections/AccordionSection.tsx
Labels: pr: fix & ship :ship:

#1785 #1660 Refactor main content-type sections to handle starz content
  next/src/components/sections/ArticlesSection/ArticlesFiltered.tsx
  next/src/components/sections/ArticlesSection/ArticlesSection.tsx
  next/src/services/fetchers/homepageContextFetcher.ts
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/AdminGroups.graphql
  next/src/services/graphql/queries/Sections.graphql
  next/src/services/meili/fetchers/articlesFetcher.ts
  strapi/config/plugins.meilisearch.config.ts
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.articles.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.documents.json
  strapi/config/sync/user-role.public.json
  strapi/schema.graphql
  strapi/src/components/sections/articles.json
  strapi/src/components/sections/documents.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:
