Repository bratislava/bratislava.sk, pull requests merged in 2025-05, with the labels that each got.

#1512 #1480 Remove cookieconsent and hotjar
  next/package-lock.json
  next/package.json
  next/public/locales/en/translation.json
  next/public/locales/sk/translation.json
  next/src/components/common/CookieConsent/CookieConsent.tsx
  next/src/components/common/CookieConsent/useCookieConsent.ts
  next/src/components/layouts/PageLayout.tsx
  next/src/pages/_app.tsx
Labels: pr: fix & ship :ship:

#1515 #1514 Create and use `alias` field for pages and articles
  next/src/components/common/Footer/DesktopFooter.tsx
  next/src/components/page-contents/ArticlePageContent.tsx
  next/src/components/page-contents/GeneralPageContent.tsx
  next/src/pages/[...slug].tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Pages.graphql
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1517 #1514 Export config sync, update roles and improve descriptions
  strapi/config/sync/admin-role.admin-lg0mm2j6.json
  strapi/config/sync/admin-role.tax-administrator-list-viewer-m2uehyx8.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##article.article.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json
Labels: pr: fix & ship :ship:

#1516 #1396 Implement new design for Gallery
  next/src/components/common/Gallery/Gallery.tsx
  next/src/utils/useTailwindBreakpointValue.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1519 #1518 Remove homepage Bookmarks completely from Strapi and FE
  next/public/locales/en/translation.json
  next/public/locales/sk/translation.json
  next/src/components/common/Bookmarks_Deprecated/Bookmark_Deprecated.tsx
  next/src/components/common/Bookmarks_Deprecated/Bookmarks_Deprecated.tsx
  next/src/components/page-contents/HomepageContent.tsx
  next/src/components/sections/homepage-sections/BookmarksHomepageSection.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Homepage.graphql
  strapi/config/sync/admin-role.admin-clanky-lmg395y8.json
  strapi/config/sync/admin-role.admin-lg0mm2j6.json
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.homepage-bookmark.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##homepage.homepage.json
  strapi/schema.graphql
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/components/blocks/homepage-bookmark.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1520 #1513 Cleanup redirects and add new redirects
  next/next.config.js
Labels: pr: fix & ship :ship:

#1522 #1463 implement new naming for tokens
  next/src/components/styleguide/showcases/TokensShowcase.tsx
  next/src/pages/styleguide.tsx
  next/src/styles/colors.css
  next/tailwind.config.colors.js
Labels: pr: fix & ship :ship:

#1523 Fix cypress tests after CookieBot was introduced
  tests/cypress/e2e/404Page.cy.ts
  tests/cypress/e2e/accountButton.cy.ts
  tests/cypress/e2e/englishTranslation.cy.ts
  tests/cypress/e2e/homepageSearch.cy.ts
  tests/cypress/e2e/officialBoard.cy.ts
  tests/cypress/e2e/organizationalStructure.cy.ts
  tests/cypress/e2e/searchPage.cy.ts
  tests/cypress/fixtures/URLsForSmokeTests.json
Labels: pr: fix & ship :ship:

#1524 #1284 Add remaining link types to `getLinkProps` function
  next/src/components/cards/ArticleCard.tsx
  next/src/components/cards/CategoryCard.tsx
  next/src/components/cards/HomepageHorizontalCard.tsx
  next/src/components/cards/InBaCard.tsx
  next/src/components/cards/MayorAndCouncilCard.tsx
  next/src/components/cards/TopServicesItem.tsx
  next/src/components/common/Banner/Banner.tsx
  next/src/components/common/Footer/FooterShared.tsx
  next/src/components/common/Links/Links.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NavBar/NavMenu/MobileNavMenu.tsx
  next/src/components/common/NavBar/NavMenu/getParsedMenus.ts
  next/src/components/common/PageHeader/PageHeader.tsx
  next/src/components/common/SubpageList_Deprecated/SubpageList_Deprecated.tsx
  next/src/components/sections/AccordionSection.tsx
  next/src/components/sections/LinksSection.tsx
  next/src/components/sections/SubpageListPageHeaderSection_Deprecated.tsx
  next/src/components/sections/homepage-sections/EventsHomepageSection.tsx
  next/src/components/sections/homepage-sections/HighlightsHomepageSection.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelLatestNews.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelOfficialBoard.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelRoadClosures.tsx
  next/src/components/sections/homepage-sections/MayorAndCouncilHomepageSection.tsx
  next/src/components/styleguide/showcases/ArticleCardShowcase.tsx
  next/src/components/styleguide/showcases/CategoryCardShowcase.tsx
  next/src/components/styleguide/showcases/HomepageHorizontalCardShowcase.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/General.graphql
  next/src/services/graphql/queries/Sections.graphql
  next/src/utils/getCommonLinkProps.ts
  next/src/utils/getLinkProps.ts
  next/src/utils/pageUtils_Deprecated.ts
  strapi/config/sync/admin-role.admin-lg0mm2j6.json
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/admin-role.tax-administrator-list-viewer-m2uehyx8.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.bookmark-link.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.common-link.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.page-link.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##general.header-link.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##menu.menu-link.json
  strapi/schema.graphql
  strapi/src/components/blocks/bookmark-link.json
  strapi/src/components/blocks/common-link.json
  strapi/src/components/blocks/page-link.json
  strapi/src/components/general/header-link.json
  strapi/src/components/menu/menu-link.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1526 #1521 Fix breadcrumbs homepage link
  next/src/components/common/Breadcrumbs/DesktopBreadcrumbs.tsx
  next/src/components/common/Breadcrumbs/MobileBreadcrumbs.tsx
Labels: pr: fix & ship :ship:

#1525 #1284 Use CommonLinkProps type and getLinkProps also in Menu
  next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuSection.tsx
  next/src/components/common/NavBar/NavMenu/getParsedMenus.ts
  next/src/components/common/NavBar/NavMenu/navMenuTypes.ts
  next/src/components/common/SubpageList_Deprecated/SubpageList_Deprecated.tsx
  next/src/utils/getLinkProps.ts
Labels: pr: fix & ship :ship:

#1531 #1286 Use NOT_FOUND const with revalidate
  next/src/pages/[...slug].tsx
  next/src/pages/inba/archiv/[slug].tsx
  next/src/pages/inba/clanky/[slug].tsx
  next/src/pages/index.tsx
  next/src/pages/spravy/[slug].tsx
  next/src/pages/styleguide.tsx
  next/src/pages/uradna-tabula/[slug].tsx
  next/src/pages/vyhladavanie.tsx
  next/src/pages/vzn/[slug].tsx
  next/src/utils/consts.ts
Labels: pr: fix & ship :ship:

#1530 #1075 Add events section to page section
  next/src/components/layouts/Sections.tsx
  next/src/components/page-contents/HomepageContent.tsx
  next/src/components/sections/TootootEventsSection.tsx
  next/src/components/sections/homepage-sections/EventsHomepageSection.tsx
  next/src/components/sections/homepage-sections/InbaHomepageSection.tsx
  next/src/pages/index.tsx
  next/src/services/fetchers/homepageContextFetcher.ts
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Homepage.graphql
  next/src/services/graphql/queries/Pages.graphql
  next/src/services/graphql/queries/Sections.graphql
  next/src/services/tootoot/tootootEvents.fetcher.tsx
  next/src/utils/dev/strapiHelper.ts
  next/src/utils/prefetchPageSections.ts
  strapi/config/sync/admin-role.admin-clanky-lmg395y8.json
  strapi/config/sync/admin-role.admin-in-ba-lmg3a62g.json
  strapi/config/sync/admin-role.admin-lg0mm2j6.json
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.homepage-inba.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.tootoot-events.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##homepage.homepage.json
  strapi/schema.graphql
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/sections/homepage-inba.json
  strapi/src/components/sections/tootoot-events.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1533 #1532 Make title required and short in Pages
  next/src/components/sections/SearchSection/useQueryBySearchOption.ts
  next/src/services/graphql/index.ts
  next/src/utils/dev/strapiHelper.ts
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##page.page.json
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#1534 #1075 Revert changes in inba homepage section
  next/src/components/page-contents/HomepageContent.tsx
  next/src/components/sections/homepage-sections/InbaHomepageSection.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Homepage.graphql
  strapi/schema.graphql
  strapi/src/api/homepage/content-types/homepage/schema.json
  strapi/src/components/sections/homepage-inba.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1541 #1539 Fix bug showing undefined link in accordions
  next/src/components/sections/AccordionSection.tsx
Labels: pr: needs review :pray:

#1542 #1419 Add aria-labelledby attributes to cards
  next/package-lock.json
  next/package.json
  next/src/components/cards/ArticleCard.tsx
  next/src/components/cards/CategoryCard.tsx
  next/src/components/cards/HomepageHorizontalCard.tsx
  next/src/components/cards/InBaCard.tsx
  next/src/components/cards/MayorAndCouncilCard.tsx
  next/src/components/cards/TopServicesItem.tsx
Labels: pr: fix & ship :ship:

#1549 #1548 Add CTA buttons to Text with image sections
  next/src/components/common/Timeline/Timeline.tsx
  next/src/components/sections/TextWithImageOverlappedSection.tsx
  next/src/components/sections/TextWithImageSection.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Sections.graphql
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.text-with-image-overlapped.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.text-with-image.json
  strapi/schema.graphql
  strapi/src/components/sections/text-with-image-overlapped.json
  strapi/src/components/sections/text-with-image.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#1551 #1550 Add title to ColumnedText section and remove contentAlignment
  next/public/locales/en/translation.json
  next/public/locales/sk/translation.json
  next/src/components/common/ColumnedText/ColumnedText.tsx
  next/src/components/sections/ColumnedTextSection.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Sections.graphql
  next/src/utils/dev/strapiHelper.ts
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.columned-text.json
  strapi/schema.graphql
  strapi/src/components/sections/columned-text.json
  strapi/types/generated/components.d.ts
Labels: pr: needs review :pray:

#1571 #1558 Add Partners section
  next/src/components/layouts/Sections.tsx
  next/src/components/sections/ColumnsSection.tsx
  next/src/components/sections/PartnersSection.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Sections.graphql
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.partner.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.partners.json
  strapi/schema.graphql
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/components/blocks/partner.json
  strapi/src/components/sections/partners.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1572 #1415 Fix issues around unlabelled icon buttons
  next/public/locales/en/translation.json
  next/public/locales/sk/translation.json
  next/src/components/common/ColumnsSectionItem/ColumnsSectionItem.tsx
  next/src/components/common/HomepageSearch/HomePageSearchField.tsx
  next/src/components/common/NavBar/AlertBanner.tsx
  next/src/components/sections/ShareButtons.tsx
Labels: pr: fix & ship :ship:
