Repository bratislava/bratislava.sk, pull requests merged in 2025-03, with the labels that each got.

#1407 #1303 Remove legacy FileList section fields
  next/services/graphql/index.ts
  strapi/schema.graphql
  strapi/src/components/blocks/file.json
  strapi/src/components/sections/file-list.json
Labels: pr: fix & ship :ship:

#1404 Replace local ginis wrapper with ginis-sdk
  .github/workflows/cypress-test.yml
  .github/workflows/pull.yml
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/.nvmrc
  next/Dockerfile
  next/ginis-sdk/api/json/gin/Detail-funkcniho-mista.ts
  next/ginis-sdk/api/json/gin/Detail-referenta.ts
  next/ginis-sdk/api/json/gin/index.ts
  next/ginis-sdk/api/json/pod/Detail-el-podani.ts
  next/ginis-sdk/api/json/pod/index.ts
  next/ginis-sdk/api/json/ssl/Detail-dokumentu.ts
  next/ginis-sdk/api/json/ssl/Pridat-soubor.ts
  next/ginis-sdk/api/json/ssl/index.ts
  next/ginis-sdk/api/json/ude/detail-dokumentu.ts
  next/ginis-sdk/api/json/ude/index.ts
  next/ginis-sdk/api/json/ude/nacist-soubor.ts
  next/ginis-sdk/api/json/ude/seznam-dokumentu.ts
  next/ginis-sdk/api/json/ude/seznam-kategorii.ts
  next/ginis-sdk/api/xml/ssl.ts
  next/ginis-sdk/api/xml/ude.ts
  next/ginis-sdk/ginis.ts
  next/ginis-sdk/index.ts
  next/ginis-sdk/utils/api.ts
  next/ginis-sdk/utils/errors.ts
  next/ginis-sdk/utils/types.ts
  next/package.json
  next/pages/api/ginis/official-board-detail/[documentId].ts
  next/pages/api/ginis/official-board-file/[fileId]/[fileName].ts
  next/services/ginis/ginis.ts
  next/services/ginis/server/getOfficialBoardFileBase64Encoded.ts
  next/services/ginis/server/getOfficialBoardParsedCategories.ts
  next/services/ginis/server/getOfficialBoardParsedDocument.ts
  next/services/ginis/server/getOfficialBoardParsedList.ts
  next/services/ginis/types.ts
  next/yarn.lock
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1423 #1422 Upgrade Strapi to v4.11.4
  strapi/database/migrations/2023.06.14T00.00.00.update-file-paths.js
  strapi/package.json
  strapi/patches/@strapi+admin+4.11.4.patch
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#1426 Change "Check for cluster conditions" pipeline to run on github runners
  .github/workflows/deploy.yml
Labels: pr: fix & ship :ship:

#1427 #1412 Upgrade Strapi to v4.14.0
  strapi/package.json
  strapi/patches/@strapi+admin+4.14.0.patch
  strapi/schema.graphql
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#1428 #1425 Upgrade Strapi to v4.15.5
  strapi/.gitignore
  strapi/package.json
  strapi/patches/@strapi+admin+4.14.0.patch
  strapi/patches/@strapi+admin+4.15.5.patch
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#1430 Use actions/upload-artifact@v4
  .github/workflows/codeql-analysis.yml
  .github/workflows/cypress-test.yml
Labels: pr: fix & ship :ship:

#1433 Major upgrade of Node, Strapi and change to npm
  .github/workflows/pull.yml
  next/.nvmrc
  next/Dockerfile
  next/components/styleguide/showcases/SnackbarShowCase.tsx
  next/package-lock.json
  next/package.json
  next/yarn.lock
  strapi/Dockerfile
  strapi/config/middlewares.ts
  strapi/package-lock.json
  strapi/package.json
  strapi/patches/@strapi+admin+4.15.5.patch
  strapi/patches/@strapi+admin+4.25.21.patch
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
  strapi/yarn.lock
Labels: pr: fix & ship :ship:

#1283 Switch to new validate TS pipeline from Bratislava's action repo
  .github/workflows/pull.yml
  .github/workflows/validate.yml
Labels: pr: needs review :pray:, pr: infrastructure

#1434 Update next, axios, react and change yarn to npm in scripts and readme
  next/.prettierignore
  next/README.md
  next/components/common/Bookmarks_Deprecated/Bookmark_Deprecated.tsx
  next/next-env.d.ts
  next/package-lock.json
  next/package.json
  next/pages/_app.tsx
  strapi/.prettierignore
  strapi/README.md
  strapi/package-lock.json
  strapi/package.json
Labels: pr: fix & ship :ship:

#1436 Switch to npm in /tests
  .github/workflows/cypress-test.yml
  strapi/package.json
  tests/README.md
  tests/package-lock.json
  tests/package.json
  tests/yarn.lock
  yarn.lock
Labels: pr: fix & ship :ship:

#985 feat: added KEDA (HPA) Prometheus scalers
  next/kubernetes/envs/Dev/kustomization.yml
  next/kubernetes/envs/Dev/scaler.yml
  next/kubernetes/envs/Prod/kustomization.yml
  next/kubernetes/envs/Prod/scaler.yml
  next/kubernetes/envs/Staging/kustomization.yml
  next/kubernetes/envs/Staging/scaler.yml
  strapi/kubernetes/envs/Dev/config.json
  strapi/kubernetes/envs/Dev/kustomization.yml
  strapi/kubernetes/envs/Dev/scaler.yml
  strapi/kubernetes/envs/Prod/config.json
  strapi/kubernetes/envs/Prod/kustomization.yml
  strapi/kubernetes/envs/Prod/scaler.yml
  strapi/kubernetes/envs/Staging/config.json
  strapi/kubernetes/envs/Staging/kustomization.yml
  strapi/kubernetes/envs/Staging/scaler.yml
Labels: pr: infrastructure

#1438 #1437 Remove legacy content type "VZN"
  next/components/layouts/PageHeaderSections.tsx
  next/components/page-contents/BlogPostPageContent.tsx
  next/components/page-contents/HomepageContent.tsx
  next/components/styleguide/showcases/TagShowCase.tsx
  next/pages/api/ginis/official-board-categories.ts
  next/pages/api/ginis/official-board-detail/[documentId].ts
  next/pages/api/ginis/official-board-list.ts
  next/services/ginis/server/api-data.dto.ts
  next/services/ginis/server/getOfficialBoardFileBase64Encoded.ts
  next/services/ginis/server/getOfficialBoardParsedCategories.ts
  next/services/ginis/server/getOfficialBoardParsedDocument.ts
  next/services/ginis/server/getOfficialBoardParsedList.ts
  next/services/graphql/index.ts
  next/services/graphql/queries/Vzn.graphql
  next/services/meili/types.ts
  strapi/schema.graphql
  strapi/src/api/vzn/content-types/vzn/schema.json
  strapi/src/api/vzn/controllers/vzn.ts
  strapi/src/api/vzn/routes/vzn.ts
  strapi/src/api/vzn/services/vzn.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1441 #1442 Cleanup strapi
  next/src/components/common/ColumnedText/ColumnedText.tsx
  next/src/components/common/IconTitleDescItem/IconTitleDescItem.tsx
  next/src/components/common/Links/Links.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NumericalList_Deprecated/NumericalListItem_Deprecated.tsx
  next/src/components/common/NumericalList_Deprecated/NumericalList_Deprecated.tsx
  next/src/components/common/SubpageList_Deprecated/SubpageList_Deprecated.tsx
  next/src/components/formatting/Markdown/Markdown.tsx
  next/src/components/layouts/Sections.tsx
  next/src/components/sections/ArticlesListSection/BlogPostsByTags.tsx
  next/src/components/sections/ColumnedTextSection.tsx
  next/src/components/sections/FeaturedBlogPostsSection.tsx
  next/src/components/sections/IconTitleDescSection.tsx
  next/src/components/sections/NumericalListSection.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Sections.graphql
  next/src/utils/pageUtils_Deprecated.ts
  strapi/schema.graphql
  strapi/src/admin/app.tsx
  strapi/src/api/faq-category/content-types/faq-category/schema.json
  strapi/src/api/faq/content-types/faq/schema.json
  strapi/src/api/footer/content-types/footer/schema.json
  strapi/src/api/general/content-types/general/schema.json
  strapi/src/api/page-category/content-types/page-category/schema.json
  strapi/src/api/page-subcategory/content-types/page-subcategory/schema.json
  strapi/src/api/page-subcategory/controllers/page-subcategory.ts
  strapi/src/api/page-subcategory/routes/page-subcategory.ts
  strapi/src/api/page-subcategory/services/page-subcategory.ts
  strapi/src/api/page/content-types/page/schema.json
  strapi/src/api/regulation/content-types/regulation/schema.json
  strapi/src/api/tax-administrators-list/content-types/tax-administrators-list/schema.json
  strapi/src/components/blocks/doc-list-extensions.json
  strapi/src/components/blocks/footer-section.json
  strapi/src/components/blocks/gallery-item.json
  strapi/src/components/blocks/page-link.json
  strapi/src/components/blocks/space-info.json
  strapi/src/components/blocks/subpage.json
  strapi/src/components/os-items/advanced-accordion-department.json
  strapi/src/components/os-items/advanced-accordion-item.json
  strapi/src/components/os-items/advanced-accordion-sub-item.json
  strapi/src/components/os-items/advanced-accordion-sub-sub-item.json
  strapi/src/components/sections/accordion.json
  strapi/src/components/sections/blog-posts-by-tags.json
  strapi/src/components/sections/columned-text.json
  strapi/src/components/sections/divider.json
  strapi/src/components/sections/faq-categories.json
  strapi/src/components/sections/faqs.json
  strapi/src/components/sections/featured-blog-posts.json
  strapi/src/components/sections/gallery.json
  strapi/src/components/sections/icon-title-desc.json
  strapi/src/components/sections/inba-releases.json
  strapi/src/components/sections/links.json
  strapi/src/components/sections/narrow-text.json
  strapi/src/components/sections/numerical-list.json
  strapi/src/components/sections/organizational-structure.json
  strapi/src/components/sections/space.json
  strapi/src/components/sections/subpage-list.json
  strapi/src/components/sections/text-with-image.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1460 #1459 Use eslint plugins next, i18n, tanstack
  next/.eslintrc.js
  next/package-lock.json
  next/package.json
  next/src/pages/api/ginis/official-board-file/[fileId]/[fileName].ts
  next/src/pages/uradna-tabula/[slug].tsx
Labels: pr: fix & ship :ship:

#1458 #1457 Update Strapi to v4.25.22
  strapi/package-lock.json
  strapi/package.json
Labels: pr: fix & ship :ship:

#1461 Add release comments workflow
  .github/workflows/comment-after-release.yml
Labels: pr: fix & ship :ship:

#1456 #1322 change footer text from plain text to richtext
  next/src/components/common/Footer/DesktopFooter.tsx
  next/src/components/common/Footer/Footer.tsx
  next/src/components/common/Footer/FooterShared.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/General.graphql
  strapi/config/sync/admin-role.admin-lg0mm2j6.json
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.footer-contact-item.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##footer.footer.json
  strapi/schema.graphql
  strapi/src/api/footer/content-types/footer/schema.json
  strapi/src/components/blocks/footer-contact-item.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1462 #1431 Update to Node 20.19
  next/Dockerfile
  next/package-lock.json
  next/package.json
  strapi/Dockerfile
  strapi/package-lock.json
  strapi/package.json
  tests/cypress/e2e/accountButton.cy.ts
  tests/package-lock.json
  tests/package.json
Labels: pr: fix & ship :ship:
