Repository bratislava/bratislava.sk, pull requests merged in 2025-04, with the labels that each got.

#1465 #1466 Change to proper sitemap path
  next/next.config.js
Labels: pr: fix & ship :ship:

#1466 Run patch-package for newer Strapi version
  strapi/patches/@strapi+admin+4.25.22.patch
Labels: pr: needs review :pray:

#1467 #1329 update button component according to ds to black color
  bratislava.sk.code-workspace
  next/src/components/cards/BlogPostCard.tsx
  next/src/components/cards/CategoryCard.tsx
  next/src/components/cards/HomepageHorizontalCard.tsx
  next/src/components/cards/InBaCard.tsx
  next/src/components/cards/MayorAndCouncilCard.tsx
  next/src/components/cards/TopServicesItem.tsx
  next/src/components/common/Banner/Banner.tsx
  next/src/components/common/Bookmarks_Deprecated/Bookmark_Deprecated.tsx
  next/src/components/common/Breadcrumbs/MobileBreadcrumbs.tsx
  next/src/components/common/Button/Button.tsx
  next/src/components/common/Carousel/Carousel.tsx
  next/src/components/common/CookieConsent/CookieConsent.tsx
  next/src/components/common/Gallery/GalleryModal.tsx
  next/src/components/common/Gallery/ImageLightBox.tsx
  next/src/components/common/HomepageSearch/HomePageSearchField.tsx
  next/src/components/common/Institution_Deprecated/Institution_Deprecated.tsx
  next/src/components/common/Links/Links.tsx
  next/src/components/common/ModalDialog/Dialog.tsx
  next/src/components/common/NavBar/NavBarHeader/NavBarHeader.tsx
  next/src/components/common/NavBar/NavMenu/MobileNavMenu.tsx
  next/src/components/common/NavBar/NavMenu/NavMenuLink.tsx
  next/src/components/common/NumericalList_Deprecated/NumericalList_Deprecated.tsx
  next/src/components/common/PageHeader/PageHeader.tsx
  next/src/components/common/Pagination/Pagination.tsx
  next/src/components/common/SkipToContentButton/SkipToContentButton.tsx
  next/src/components/common/SubpageList_Deprecated/SubpageList_Deprecated.tsx
  next/src/components/sections/AccordionSection.tsx
  next/src/components/sections/CalculatorSection_Deprecated/MinimumCalculator_Deprecated.tsx
  next/src/components/sections/SearchSection/SearchResultsHeader.tsx
  next/src/components/sections/homepage-sections/EventsHomepageSection.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelLatestNews.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelOfficialBoard.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelRoadClosures.tsx
  next/src/components/sections/homepage-sections/WelcomeHomepageSection.tsx
  next/src/components/styleguide/showcases/ButtonShowCase.tsx
  next/src/pages/404.tsx
Labels: pr: fix & ship :ship:

#1469 #1468 Enable phone number in Richtext
  next/src/components/formatting/Markdown/Markdown.tsx
Labels: pr: fix & ship :ship:

#1472 #1325 Remove 6 main cards in welcome section + minor improvements in footer
  next/src/components/cards/WelcomeCard/IconComponents/IconCity.tsx
  next/src/components/cards/WelcomeCard/IconComponents/IconCulture.tsx
  next/src/components/cards/WelcomeCard/IconComponents/IconEducation.tsx
  next/src/components/cards/WelcomeCard/IconComponents/IconEnvironment.tsx
  next/src/components/cards/WelcomeCard/IconComponents/IconSocial.tsx
  next/src/components/cards/WelcomeCard/IconComponents/IconTransport.tsx
  next/src/components/cards/WelcomeCard/WelcomeCard.tsx
  next/src/components/cards/WelcomeCard/WelcomeCardIcon.tsx
  next/src/components/common/Accordion/Accordion.tsx
  next/src/components/common/Footer/DesktopFooter.tsx
  next/src/components/sections/homepage-sections/WelcomeHomepageSection.tsx
Labels: pr: fix & ship :ship:

#1473 #1397 Remove shadows
  next/src/components/cards/CardBase.tsx
  next/src/components/cards/EventCard.tsx
  next/src/components/cards/InBaCard.tsx
  next/src/components/cards/MayorAndCouncilCard.tsx
  next/src/components/common/FeaturedBlogPosts/FeaturedBlogPosts.tsx
  next/src/components/common/Gallery/Gallery.tsx
  next/src/components/common/Iframe/Iframe.tsx
  next/src/components/common/InbaFeaturedArticles/InbaFeaturedArticles.tsx
  next/src/components/common/NavBar/MobileNavBar.tsx
  next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordionCard_Deprecated.tsx
  next/src/components/common/Timeline/Timeline.tsx
  next/src/components/common/Videos_Deprecated/Videos_Deprecated.tsx
  next/src/components/page-contents/InbaReleasePageContent.tsx
  next/src/components/sections/ArticlesListSection/BlogPostsByCategory.tsx
  next/src/components/sections/ArticlesListSection/BlogPostsList.tsx
  next/src/components/sections/ArticlesListSection/InbaArticlesList.tsx
  next/src/components/sections/InbaReleasesSection.tsx
  next/src/components/sections/RelatedBlogPostsSection.tsx
  next/src/components/sections/homepage-sections/HighlightsHomepageSection.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelLatestNews.tsx
  next/src/components/styleguide/StyleGuideWrapper.tsx
  next/src/components/styleguide/showcases/BlogPostCardShowcase.tsx
  next/src/components/styleguide/showcases/CategoryCardShowcase.tsx
  next/src/components/styleguide/showcases/HomepageHorizontalCardShowcase.tsx
Labels: pr: fix & ship :ship:

#1471 #1398 make the menu non sticky
  next/public/locales/en/translation.json
  next/public/locales/sk/translation.json
  next/src/components/common/NavBar/NavBar.tsx
  next/src/components/common/NavBar/NavMenu/NavMenu.tsx
  next/src/components/common/ScrollToTopButton/ScrollToTopButton.tsx
  next/src/components/layouts/PageLayout.tsx
Labels: pr: fix & ship :ship:

#1475 #1384 #1391 Improve markdown margins and tables
  next/src/components/formatting/Markdown/Markdown.module.scss
  next/src/components/formatting/Markdown/Markdown.tsx
Labels: pr: fix & ship :ship:

#1476 #1453 Implement GTM
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.prod
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/kubernetes/envs/Dev/.env
  next/kubernetes/envs/Staging/.env
  next/package-lock.json
  next/package.json
  next/src/components/common/Button/Button.tsx
  next/src/components/common/MLink/MLink.tsx
  next/src/pages/_app.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/General.graphql
  next/src/utils/getCommonLinkProps.ts
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.common-link.json
  strapi/schema.graphql
  strapi/src/components/blocks/common-link.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#1479 Fix validate.yml directory param
  .github/workflows/validate.yml
Labels: pr: fix & ship :ship:

#1478 Secret cleanup and added Mailgun & Strapi revalidate secret
  .github/workflows/validate.yml
  next/kubernetes/base/deployment.yml
  next/kubernetes/base/secrets/strapi-revalidate.secret.dev.yml
  next/kubernetes/base/secrets/strapi-revalidate.secret.prod.yml
  next/kubernetes/base/secrets/strapi-revalidate.secret.staging.yml
  strapi/kubernetes/base/deployment.yml
  strapi/kubernetes/base/secrets/database.yml
  strapi/kubernetes/base/secrets/meilisearch.yml
  strapi/kubernetes/base/secrets/minio.secret.yml
  strapi/kubernetes/base/secrets/strapi.yml
  strapi/kubernetes/envs/Dev/kustomization.yml
  strapi/kubernetes/envs/Dev/secrets/database.secret.yml
  strapi/kubernetes/envs/Dev/secrets/mailgun.secret.yml
  strapi/kubernetes/envs/Dev/secrets/meilisearch.secret.yml
  strapi/kubernetes/envs/Dev/secrets/revalidate.secret.yml
  strapi/kubernetes/envs/Dev/secrets/strapi.secret.yml
  strapi/kubernetes/envs/Prod/kustomization.yml
  strapi/kubernetes/envs/Prod/secrets/database.secret.yml
  strapi/kubernetes/envs/Prod/secrets/mailgun.secret.yml
  strapi/kubernetes/envs/Prod/secrets/meilisearch.secret.yml
  strapi/kubernetes/envs/Prod/secrets/revalidate.secret.yml
  strapi/kubernetes/envs/Prod/secrets/strapi.secret.yml
  strapi/kubernetes/envs/Staging/kustomization.yml
  strapi/kubernetes/envs/Staging/secrets/database.secret.yml
  strapi/kubernetes/envs/Staging/secrets/mailgun.secret.yml
  strapi/kubernetes/envs/Staging/secrets/meilisearch.secret.yml
  strapi/kubernetes/envs/Staging/secrets/revalidate.secret.yml
  strapi/kubernetes/envs/Staging/secrets/strapi.secret.yml
Labels: pr: needs review :pray:

#1485 #1332 Quickfix dividers and borders for file lists
  next/src/components/common/Divider/HorizontalDivider.tsx
  next/src/components/common/FileList/FileList.tsx
  next/src/components/page-contents/InbaReleasePageContent.tsx
  next/src/components/page-contents/OfficialBoardDocumentPageContent.tsx
  next/src/components/page-contents/RegulationPageContent.tsx
  next/src/components/sections/SearchSection/SearchResultCard.tsx
  next/src/components/sections/SearchSection/SearchResults.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelOfficialBoard.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Sections.graphql
Labels: pr: fix & ship :ship:

#1487 #1486 Make BlogPost title required and short
  next/src/components/common/Bookmarks_Deprecated/Bookmark_Deprecated.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/BlogPosts.graphql
  next/src/utils/dev/strapiHelper.ts
  strapi/config/sync/admin-role.admin-clanky-lmg395y8.json
  strapi/config/sync/admin-role.admin-in-ba-lmg3a62g.json
  strapi/schema.graphql
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#1489 #1486 Remove `author` field from BlogPosts
  next/src/services/graphql/index.ts
  next/src/utils/dev/strapiHelper.ts
  strapi/config/sync/admin-role.admin-clanky-lmg395y8.json
  strapi/config/sync/admin-role.admin-in-ba-lmg3a62g.json
  strapi/config/sync/admin-role.admin-lg0mm2j6.json
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##api##blog-post.blog-post.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_content_types##plugin##users-permissions.user.json
  strapi/config/sync/user-role.public.json
  strapi/schema.graphql
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/src/extensions/users-permissions/content-types/user/schema.json
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#1491 #1452 Setup mailgun email provider
  strapi/.env.example
  strapi/config/plugins.ts
  strapi/config/server.ts
  strapi/kubernetes/base/.env
  strapi/kubernetes/envs/Dev/.env
  strapi/kubernetes/envs/Prod/.env
  strapi/package-lock.json
  strapi/package.json
Labels: pr: fix & ship :ship:

#1495 1452-missing-env-variable
  strapi/kubernetes/envs/Staging/.env
Labels: pr: fix & ship :ship:

#1492 #1454 Revalidate webhook implementation
  next/.env
  next/.env.bratiska-cli-build.dev
  next/.env.bratiska-cli-build.staging
  next/.env.development
  next/README.md
  next/kubernetes/envs/Prod/kustomization.yml
  next/kubernetes/envs/Prod/secrets/revalidate.secret.yml
  next/kubernetes/envs/Prod/secrets/revalidate.yml
  strapi/.env.example
  strapi/kubernetes/base/.env
  strapi/src/index.ts
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: fix & ship :ship:

#1496 #1486 Use Articles on whole page
  next/next.config.js
  next/public/locales/en/translation.json
  next/public/locales/sk/translation.json
  next/src/components/common/HomepageSearch/HomePageSearchResults.tsx
  next/src/components/layouts/Sections.tsx
  next/src/components/page-contents/GeneralPageContent.tsx
  next/src/components/sections/ArticlesListSection/ArticlesAllSection.tsx
  next/src/components/sections/ArticlesListSection/ArticlesByCategory.tsx
  next/src/components/sections/ArticlesListSection/ArticlesSection.tsx
  next/src/components/sections/RelatedArticlesSection.tsx
  next/src/components/sections/SearchSection/GlobalSearchSectionContent.tsx
  next/src/components/sections/SearchSection/useQueryBySearchOption.ts
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelLatestNews.tsx
  next/src/components/sections/homepage-sections/WelcomeHomepageSection.tsx
  next/src/pages/api/revalidate.ts
  next/src/services/fetchers/homepageContextFetcher.ts
  next/src/services/graphql/fetchers/relatedBlogPosts.fetcher.ts
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Articles.graphql
  next/src/services/graphql/queries/BlogPosts.graphql
  next/src/services/graphql/queries/General.graphql
  next/src/services/graphql/queries/Homepage.graphql
  next/src/services/graphql/queries/Sections.graphql
  next/src/services/meili/fetchers/homepageSearchFetcher.ts
  next/src/services/meili/fetchers/relatedArticlesFetcher.ts
  next/src/services/meili/types.ts
  next/src/utils/getCommonLinkProps.ts
  next/src/utils/prefetchPageSections.ts
  strapi/config/sync/admin-role.admin-clanky-lmg395y8.json
  strapi/config/sync/admin-role.admin-in-ba-lmg3a62g.json
  strapi/config/sync/admin-role.admin-lg0mm2j6.json
  strapi/config/sync/admin-role.strapi-super-admin.json
  strapi/config/sync/admin-role.tax-administrator-list-viewer-m2uehyx8.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##blocks.common-link.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.articles.json
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.homepage-tabs.json
  strapi/schema.graphql
  strapi/src/api/article/content-types/article/schema.json
  strapi/src/api/blog-post/content-types/blog-post/schema.json
  strapi/src/components/blocks/common-link.json
  strapi/src/components/sections/articles.json
  strapi/src/components/sections/homepage-tabs.json
  strapi/types/generated/components.d.ts
  strapi/types/generated/contentTypes.d.ts
Labels: pr: needs review :pray:

#1499 #1454 Revalidate Fix
  next/src/pages/api/revalidate.ts
Labels: pr: fix & ship :ship:

#1503 #1502 Move "sekretariat" and "asistent" higher in org. structure lists
  next/src/services/ms-graph/server/getGroupMembers.ts
Labels: pr: fix & ship :ship:

#1500 #1497 Simplify passing article props to ArticleCard
  next/package-lock.json
  next/package.json
  next/src/components/cards/ArticleCard.tsx
  next/src/components/cards/transformArticleProps.ts
  next/src/components/cards/transformInbaArticleProps.ts
  next/src/components/page-contents/InbaArticlePageContent.tsx
  next/src/components/sections/ArticlesListSection/ArticlesAllSection.tsx
  next/src/components/sections/ArticlesListSection/ArticlesByCategory.tsx
  next/src/components/sections/ArticlesListSection/InbaArticlesList.tsx
  next/src/components/sections/RelatedArticlesSection.tsx
  next/src/components/sections/SearchSection/useQueryBySearchOption.ts
  next/src/components/sections/homepage-sections/HomepageTabs/TabPanelLatestNews.tsx
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/InbaArticles.graphql
  next/src/services/meili/fetchers/articlesFetcher.ts
  next/src/services/meili/fetchers/inbaArticlesFetcher.ts
  next/src/services/meili/types.ts
  next/src/utils/formatDate.ts
Labels: pr: fix & ship :ship:

#1501 #1384 Cleanup text sizes
  next/src/components/cards/EventCard.tsx
  next/src/components/cards/FileRowCard.tsx
  next/src/components/common/Accordion/Accordion.tsx
  next/src/components/common/Brand/Brand.tsx
  next/src/components/common/Breadcrumbs/DesktopBreadcrumbs.tsx
  next/src/components/common/Breadcrumbs/MobileBreadcrumbs.tsx
  next/src/components/common/Chip/Chip.tsx
  next/src/components/common/Contacts/Contacts.tsx
  next/src/components/common/FaqsGroup/FaqsGroup.tsx
  next/src/components/common/Gallery/Gallery.tsx
  next/src/components/common/NumericalList_Deprecated/NumericalListItem_Deprecated.tsx
  next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordionCard_Deprecated.tsx
  next/src/components/common/Tag/Tag.tsx
  next/src/components/formatting/Markdown/Markdown.tsx
  next/src/components/page-contents/ArticlePageContent.tsx
  next/src/components/sections/CalculatorSection_Deprecated/MinimumCalculator_Deprecated.tsx
  next/src/components/sections/TestimonialsSection.tsx
  next/src/components/sections/homepage-sections/HomepageTabs/HomepageTabs.tsx
  next/src/components/styleguide/Stack.tsx
  next/src/components/styleguide/showcases/MarkdownShowcase.tsx
  next/src/pages/styleguide.tsx
  next/src/styles/globals.css
  next/tailwind.config.js
Labels: pr: fix & ship :ship:

#1505 #1504 Remove unused fields from Regulations list section
  next/src/services/graphql/index.ts
  next/src/services/graphql/queries/Sections.graphql
  strapi/config/sync/core-store.plugin_content_manager_configuration_components##sections.regulations-list.json
  strapi/schema.graphql
  strapi/src/components/sections/regulations-list.json
  strapi/types/generated/components.d.ts
Labels: pr: fix & ship :ship:

#1509 #1508 Use RegulationRowCard in Regulations section
  next/public/locales/en/translation.json
  next/public/locales/sk/translation.json
  next/src/components/cards/RegulationCard/RegulationCard.tsx
  next/src/components/cards/RegulationRowCard.tsx
  next/src/components/common/Regulations/RegulationDetailMessage.tsx
  next/src/components/common/Regulations/Regulations.tsx
  next/src/components/page-contents/RegulationPageContent.tsx
  next/src/utils/getRegulationMetadata.ts
Labels: pr: fix & ship :ship:, pr: needs review :pray:

#1506 #1507 Minor improvements in organizational structure FE
  next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordionCard_Deprecated.tsx
  next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordionCards_Deprecated.tsx
  next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureAccordion_Deprecated.tsx
  next/src/components/common/OrganizationalStructure_Deprecated/OrganizationalStructureTopLevelAccordion_Deprecated.tsx
  tests/cypress/e2e/organizationalStructure.cy.ts
Labels: pr: needs review :pray:
